Route102_EventScript_ItemPotion:: @ 8290CD8
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Potion
	closemessage
	end

Route103_EventScript_ItemGuardSpec:: @ 8290CE5
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Guard_Spec
	closemessage
	end

Route103_EventScript_ItemPPUp:: @ 8290CF2
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_PP_Up
	closemessage
	end

Route104_EventScript_ItemPPUp:: @ 8290CFF
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_PP_Up
	closemessage
	end

Route104_EventScript_ItemPokeBall:: @ 8290D0C
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Poke_Ball
	closemessage
	end

Route104_EventScript_ItemXAccuracy:: @ 8290D19
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_X_Accuracy
	closemessage
	end

Route104_EventScript_ItemPotion:: @ 8290D26
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Potion
	closemessage
	end

Route105_EventScript_ItemIron:: @ 8290D33
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Iron
	closemessage
	end

Route106_EventScript_ItemProtein:: @ 8290D40
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Protein
	closemessage
	end

Route108_EventScript_ItemStarPiece:: @ 8290D4D
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Star_Piece
	closemessage
	end

Route109_EventScript_ItemPPUp:: @ 8290D5A
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_PP_Up
	closemessage
	end

Route109_EventScript_ItemPotion:: @ 8290D67
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Potion
	closemessage
	end

Route110_EventScript_ItemRareCandy:: @ 8290D74
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Rare_Candy
	closemessage
	end

Route110_EventScript_ItemDireHit:: @ 8290D81
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Dire_Hit
	closemessage
	end

Route110_EventScript_ItemElixir:: @ 8290D8E
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Elixir
	closemessage
	end

Route111_EventScript_ItemTM37:: @ 8290D9B
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_TM37
	closemessage
	end

Route111_EventScript_ItemStardust:: @ 8290DA8
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Stardust
	closemessage
	end

Route111_EventScript_ItemHPUp:: @ 8290DB5
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_HP_Up
	closemessage
	end

Route111_EventScript_ItemElixir:: @ 8290DC2
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Elixir
	closemessage
	end

Route112_EventScript_ItemNugget:: @ 8290DCF
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Nugget
	closemessage
	end

Route113_EventScript_ItemMaxEther:: @ 8290DDC
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Max_Ether
	closemessage
	end

Route113_EventScript_ItemSuperRepel:: @ 8290DE9
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Super_Repel
	closemessage
	end

Route113_EventScript_ItemHyperPotion:: @ 8290DF6
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Hyper_Potion
	closemessage
	end

Route114_EventScript_ItemRareCandy:: @ 8290E03
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Rare_Candy
	closemessage
	end

Route114_EventScript_ItemProtein:: @ 8290E10
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Protein
	closemessage
	end

Route114_EventScript_ItemEnergyPowder:: @ 8290E1D
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Energy_Powder
	closemessage
	end

Route115_EventScript_ItemSuperPotion:: @ 8290E2A
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Super_Potion
	closemessage
	end

Route115_EventScript_ItemTM01:: @ 8290E37
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_TM01
	closemessage
	end

Route115_EventScript_ItemIron:: @ 8290E44
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Iron
	closemessage
	end

Route115_EventScript_ItemGreatBall:: @ 8290E51
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Great_Ball
	closemessage
	end

Route115_EventScript_ItemHealPowder:: @ 8290E5E
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Heal_Powder
	closemessage
	end

Route115_EventScript_ItemPPUp:: @ 8290E6B
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_PP_Up
	closemessage
	end

Route116_EventScript_ItemXSpecial:: @ 8290E78
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_X_Special
	closemessage
	end

Route116_EventScript_ItemEther:: @ 8290E85
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Ether
	closemessage
	end

Route116_EventScript_ItemRepel:: @ 8290E92
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Repel
	closemessage
	end

Route116_EventScript_ItemHPUp:: @ 8290E9F
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_HP_Up
	closemessage
	end

Route116_EventScript_ItemPotion:: @ 8290EAC
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Potion
	closemessage
	end

Route117_EventScript_ItemGreatBall:: @ 8290EB9
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Great_Ball
	closemessage
	end

Route117_EventScript_ItemRevive:: @ 8290EC6
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Revive
	closemessage
	end

Route118_EventScript_ItemHyperPotion:: @ 8290ED3
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Hyper_Potion
	closemessage
	end

Route119_EventScript_ItemSuperRepel:: @ 8290EE0
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Super_Repel
	closemessage
	end

Route119_EventScript_ItemZinc:: @ 8290EED
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Zinc
	closemessage
	end

Route119_EventScript_ItemElixir:: @ 8290EFA	
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Elixir
	closemessage
	end

Route119_EventScript_ItemLeafStone:: @ 8290F07
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Leaf_Stone
	closemessage
	end

Route119_EventScript_ItemRareCandy:: @ 8290F14
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Rare_Candy
	closemessage
	end

Route119_EventScript_ItemHyperPotion:: @ 8290F21
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Hyper_Potion
	closemessage
	end

Route119_EventScript_ItemHyperPotion2:: @ 8290F2E
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Hyper_Potion
	closemessage
	end

Route119_EventScript_ItemElixir2:: @ 8290F3B
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Elixir
	closemessage
	end

Route120_EventScript_ItemNugget:: @ 8290F48
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Nugget
	closemessage
	end

Route120_EventScript_ItemFullHeal:: @ 8290F55
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Full_Heal
	closemessage
	end

Route120_EventScript_ItemHyperPotion:: @ 8290F62
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Hyper_Potion
	closemessage
	end

Route120_EventScript_ItemNestBall:: @ 8290F6F
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Nest_Ball
	closemessage
	end

Route120_EventScript_ItemRevive:: @ 8290F7C
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Revive
	closemessage
	end

Route121_EventScript_ItemCarbos:: @ 8290F89
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Carbos
	closemessage
	end

Route121_EventScript_ItemRevive:: @ 8290F96
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Revive
	closemessage
	end

Route121_EventScript_ItemZinc:: @ 8290FA3
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Zinc
	closemessage
	end

Route123_EventScript_ItemCalcium:: @ 8290FB0
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Calcium
	closemessage
	end

Route123_EventScript_ItemUltraBall:: @ 8290FBD
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Ultra_Ball
	closemessage
	end

Route123_EventScript_ItemElixir:: @ 8290FCA
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Elixir
	closemessage
	end

Route123_EventScript_ItemPPUp:: @ 8290FD7
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_PP_Up
	closemessage
	end

Route123_EventScript_ItemRevivalHerb:: @ 8290FE4
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Revival_Herb
	closemessage
	end

Route124_EventScript_ItemRedShard:: @ 8290FF1
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Red_Shard
	closemessage
	end

Route124_EventScript_ItemBlueShard:: @ 8290FFE
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Blue_Shard
	closemessage
	end

Route124_EventScript_ItemYellowShard:: @ 829100B
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Yellow_Shard
	closemessage
	end

Route125_EventScript_ItemBigPearl:: @ 8291018
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Big_Pearl
	closemessage
	end

Route126_EventScript_ItemGreenShard:: @ 8291025
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Green_Shard
	closemessage
	end

Route127_EventScript_ItemZinc:: @ 8291032
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Zinc
	closemessage
	end

Route127_EventScript_ItemCarbos:: @ 829103F
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Carbos
	closemessage
	end

Route127_EventScript_ItemRareCandy:: @ 829104C
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Rare_Candy
	closemessage
	end

Route132_EventScript_ItemRareCandy:: @ 8291059
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Rare_Candy
	closemessage
	end

Route132_EventScript_ItemProtein:: @ 8291066
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Protein
	closemessage
	end

Route133_EventScript_ItemBigPearl:: @ 8291073
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Big_Pearl
	closemessage
	end

Route133_EventScript_ItemStarPiece:: @ 8291080
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Star_Piece
	closemessage
	end

Route133_EventScript_ItemMaxRevive:: @ 829108D
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Max_Revive
	closemessage
	end

Route134_EventScript_ItemCarbos:: @ 829109A
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Carbos
	closemessage
	end

Route134_EventScript_ItemStarPiece:: @ 82910A7
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Star_Piece
	closemessage
	end

PetalburgCity_EventScript_ItemMaxRevive:: @ 82910B4
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Max_Revive
	closemessage
	end

PetalburgCity_EventScript_ItemEther:: @ 82910C1
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Ether
	closemessage
	end

MauvilleCity_EventScript_ItemXSpeed:: @ 82910CE
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_X_Speed
	closemessage
	end

RustboroCity_EventScript_ItemXDefend:: @ 82910DB
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_X_Defend
	closemessage
	end

LilycoveCity_EventScript_ItemMaxRepel:: @ 82910E8
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Max_Repel
	closemessage
	end

MossdeepCity_EventScript_ItemNetBall:: @ 82910F5
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Net_Ball
	closemessage
	end

PetalburgWoods_EventScript_ItemXAttack:: @ 8291102
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_X_Attack
	closemessage
	end

PetalburgWoods_EventScript_ItemGreatBall:: @ 829110F
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Great_Ball
	closemessage
	end

PetalburgWoods_EventScript_ItemEther:: @ 829111C
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Ether
	closemessage
	end

PetalburgWoods_EventScript_ItemParalyzeHeal:: @ 8291129
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Paralyze_Heal
	closemessage
	end

RusturfTunnel_EventScript_ItemPokeBall:: @ 8291136
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Poke_Ball
	closemessage
	end

RusturfTunnel_EventScript_ItemMaxEther:: @ 8291143
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Max_Ether
	closemessage
	end

GraniteCave_1F_EventScript_ItemEscapeRope:: @ 8291150
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Escape_Rope
	closemessage
	end

GraniteCave_B1F_EventScript_ItemPokeBall:: @ 829115D
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Poke_Ball
	closemessage
	end

GraniteCave_B2F_EventScript_ItemRepel:: @ 829116A
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Repel
	closemessage
	end

GraniteCave_B2F_EventScript_ItemRareCandy:: @ 8291177
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Rare_Candy
	closemessage
	end

JaggedPass_EventScript_ItemBurnHeal:: @ 8291184
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Burn_Heal
	closemessage
	end

FieryPath_EventScript_ItemFireStone:: @ 8291191
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Fire_Stone
	closemessage
	end

FieryPath_EventScript_ItemTM06:: @ 829119E
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_TM06
	closemessage
	end

MeteorFalls_1F_1R_EventScript_ItemTM23:: @ 82911AB
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_TM23
	closemessage
	end

MeteorFalls_1F_1R_EventScript_ItemFullHeal:: @ 82911B8
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Full_Heal
	closemessage
	end

MeteorFalls_1F_1R_EventScript_ItemMoonStone:: @ 82911C5
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Moon_Stone
	closemessage
	end

MeteorFalls_1F_1R_EventScript_ItemPPUP:: @ 82911D2
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_PP_Up
	closemessage
	end

MeteorFalls_B1F_2R_EventScript_ItemTM02:: @ 82911DF
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_TM02
	closemessage
	end

NewMauville_Inside_EventScript_ItemUltraBall:: @ 82911EC
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Ultra_Ball
	closemessage
	end

NewMauville_Inside_EventScript_ItemEscapeRope:: @ 82911F9
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Escape_Rope
	closemessage
	end

NewMauville_Inside_EventScript_ItemThunderStone:: @ 8291206
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Thunder_Stone
	closemessage
	end

NewMauville_Inside_EventScript_ItemFullHeal:: @ 8291213
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Full_Heal
	closemessage
	end

NewMauville_Inside_EventScript_ItemParalyzeHeal:: @ 8291220
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Paralyze_Heal
	closemessage
	end

AbandonedShip_Rooms_1F_EventScript_ItemHarborMail:: @ 829122D
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Harbor_Mail
	closemessage
	end

AbandonedShip_Rooms_B1F_EventScript_ItemEscapeRope:: @ 829123A
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Escape_Rope
	closemessage
	end

AbandonedShip_Rooms2_B1F_EventScript_ItemDiveBall:: @ 8291247
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Dive_Ball
	closemessage
	end

AbandonedShip_Room_B1F_EventScript_ItemTM13:: @ 8291254
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_TM13
	closemessage
	end

AbandonedShip_Rooms2_1F_EventScript_ItemRevive:: @ 8291261
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Revive
	closemessage
	end

AbandonedShip_CaptainsOffice_EventScript_ItemStorageKey:: @ 829126E
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Storage_Key
	closemessage
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemLuxuryBall:: @ 829127B
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Luxury_Ball
	closemessage
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemScanner:: @ 8291288
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Scanner
	closemessage
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemWaterStone:: @ 8291295
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Water_Stone
	closemessage
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemTM18:: @ 82912A2
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_TM18
	closemessage
	end

ScorchedSlab_EventScript_ItemTM11:: @ 82912AF
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_TM11
	closemessage
	end

SafariZone_Northwest_EventScript_ItemTM22:: @ 82912BC
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_TM22
	closemessage
	end

SafariZone_North_EventScript_ItemCalcium:: @ 82912C9
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Calcium
	closemessage
	end

SafariZone_Southwest_EventScript_ItemMaxRevive:: @ 82912D6
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Max_Revive
	closemessage
	end

SafariZone_Northeast_EventScript_ItemNugget:: @ 82912E3
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Nugget
	closemessage
	end

SafariZone_Southeast_EventScript_ItemBigPearl:: @ 82912F0
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Big_Pearl
	closemessage
	end

MtPyre_2F_EventScript_ItemUltraBall:: @ 82912FD
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Ultra_Ball
	closemessage
	end

MtPyre_3F_EventScript_ItemSuperRepel:: @ 829130A
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Super_Repel
	closemessage
	end

MtPyre_4F_EventScript_ItemSeaIncense:: @ 8291317
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Sea_Incense
	closemessage
	end

MtPyre_5F_EventScript_ItemLaxIncense:: @ 8291324
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Lax_Incense
	closemessage
	end

MtPyre_6F_EventScript_ItemTM30:: @ 8291331
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_TM30
	closemessage
	end

MtPyre_Exterior_EventScript_ItemMaxPotion:: @ 829133E
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Max_Potion
	closemessage
	end

MtPyre_Exterior_EventScript_ItemTM48:: @ 829134B
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_TM48
	closemessage
	end

AquaHideout_B1F_EventScript_ItemMasterBall:: @ 8291358
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Master_Ball
	closemessage
	end

AquaHideout_B1F_EventScript_ItemNugget:: @ 8291365
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Nugget
	closemessage
	end

AquaHideout_B1F_EventScript_ItemMaxElixir:: @ 8291372
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Max_Elixir
	closemessage
	end

AquaHideout_B2F_EventScript_ItemNestBall:: @ 829137F
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Nest_Ball
	closemessage
	end

AquaHideout_B2F_EventScript_ItemMasterBall:: @ 829138C
	finditem ITEM_MASTER_BALL      // Unused
	end

Route119_EventScript_ItemNugget:: @ 8291399
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Nugget
	closemessage
	end

Route119_EventScript_ItemMaxElixir:: @ 82913A6
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Elixir
	closemessage
	end

Route119_EventScript_ItemNestBall:: @ 82913B3
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Nest_Ball
	closemessage
	end

ShoalCave_LowTideEntranceRoom_EventScript_ItemBigPearl:: @ 82913C0
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Big_Pearl
	closemessage
	end

ShoalCave_LowTideInnerRoom_EventScript_ItemRareCandy:: @ 82913CD
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Rare_Candy
	closemessage
	end

ShoalCave_LowTideStairsRoom_EventScript_ItemIceHeal:: @ 82913DA
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Ice_Heal
	closemessage
	end

ShoalCave_LowTideIceRoom_EventScript_ItemTM07:: @ 82913E7
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_TM07
	closemessage
	end

ShoalCave_LowTideIceRoom_EventScript_ItemNeverMeltIce:: @ 82913F4
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Never_Melt_Ice
	closemessage
	end

SeafloorCavern_Room9_EventScript_ItemTM26:: @ 8291401
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_TM26
	closemessage
	end

Route110_TrickHousePuzzle1_EventScript_ItemOrangeMail:: @ 829140E
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Orange_Mail
	closemessage
	end

Route110_TrickHousePuzzle2_EventScript_ItemHarborMail:: @ 829141B
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Harbor_Mail
	closemessage
	end

Route110_TrickHousePuzzle2_EventScript_ItemWaveMail:: @ 8291428
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Wave_Mail
	closemessage
	end

Route110_TrickHousePuzzle3_EventScript_ItemShadowMail:: @ 8291435
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Shadow_Mail
	closemessage
	end

Route110_TrickHousePuzzle3_EventScript_ItemWoodMail:: @ 8291442
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Wood_Mail
	closemessage
	end

Route110_TrickHousePuzzle4_EventScript_ItemMechMail:: @ 829144F
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Mech_Mail
	closemessage
	end

Route110_TrickHousePuzzle6_EventScript_ItemGlitterMail:: @ 829145C
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Glitter_Mail
	closemessage
	end

Route110_TrickHousePuzzle7_EventScript_ItemTropicMail:: @ 8291469
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Tropic_Mail
	closemessage
	end

Route110_TrickHousePuzzle8_EventScript_ItemBeadMail:: @ 8291476
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Bead_Mail
	closemessage
	end

VictoryRoad_1F_EventScript_ItemMaxElixir:: @ 8291483
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Max_Elixir
	closemessage
	end

VictoryRoad_1F_EventScript_ItemPPUp:: @ 8291490
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_PP_Up
	closemessage
	end

VictoryRoad_B1F_EventScript_ItemTM29:: @ 829149D
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_TM29
	closemessage
	end

VictoryRoad_B1F_EventScript_ItemFullRestore:: @ 82914AA
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Full_Restore
	closemessage
	end

VictoryRoad_B2F_EventScript_ItemFullHeal:: @ 82914B7
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Full_Heal
	closemessage
	end

ArtisanCave_B1F_EventScript_ItemHPUp:: @ 82914C4
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_HP_Up
	closemessage
	end

ArtisanCave_1F_EventScript_ItemCarbos:: @ 82914D1
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Carbos
	closemessage
	end

MagmaHideout_1F_EventScript_ItemRareCandy:: @ 82914DE
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Rare_Candy
	closemessage
	end

MagmaHideout_2F_2R_EventScript_MaxElixir:: @ 82914EB
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Max_Elixir
	closemessage
	end

MagmaHideout_2F_2R_EventScript_ItemFullRestore:: @ 82914F8
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Full_Restore
	closemessage
	end

MagmaHideout_3F_1R_EventScript_ItemNugget:: @ 8291505
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Nugget
	closemessage
	end

MagmaHideout_3F_2R_EventScript_ItemPPMax:: @ 8291512
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_PP_Max
	closemessage
	end

MagmaHideout_4F_EventScript_MaxRevive:: @ 829151F
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Revive
	closemessage
	end

MagmaHideout_3F_3R_EventScript_ItemEscapeRope:: @ 829152C
	playse SE_SELECT
	waitse
	removeobject VAR_LAST_TALKED
	call GetItem_Escape_Rope
	closemessage
	end
