@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@				@
@         ITEM SCRIPTS		@		
@				@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

GetItem_Master_Ball::
	giveitem ITEM_MASTER_BALL
	return

GetItem_Ultra_Ball::
	giveitem ITEM_ULTRA_BALL
	return

GetItem_Great_Ball::
	giveitem ITEM_GREAT_BALL
	return

GetItem_Poke_Ball::
	giveitem ITEM_POKE_BALL
	return

GetItem_Safari_Ball::
	giveitem ITEM_SAFARI_BALL
	return

GetItem_Net_Ball::
	giveitem ITEM_NET_BALL
	return

GetItem_Dive_Ball::
	giveitem ITEM_DIVE_BALL
	return

GetItem_Nest_Ball::
	giveitem ITEM_NEST_BALL
	return

GetItem_Repeat_Ball::
	giveitem ITEM_REPEAT_BALL
	return

GetItem_Timer_Ball::
	giveitem ITEM_TIMER_BALL
	return

GetItem_Luxury_Ball::
	giveitem ITEM_LUXURY_BALL
	return

GetItem_Premier_Ball::
	giveitem ITEM_PREMIER_BALL
	return

GetItem_Potion::
	giveitem ITEM_POTION
	return

GetItem_Antidote::
	giveitem ITEM_ANTIDOTE
	return

GetItem_Burn_Heal::
	giveitem ITEM_BURN_HEAL
	return

GetItem_Ice_Heal::
	giveitem ITEM_ICE_HEAL
	return

GetItem_Awakening::
	giveitem ITEM_AWAKENING
	return

GetItem_Paralyze_Heal::
	giveitem ITEM_PARALYZE_HEAL
	return

GetItem_Full_Restore::
	giveitem ITEM_FULL_RESTORE
	return

GetItem_Max_Potion::
	giveitem ITEM_MAX_POTION
	return

GetItem_Hyper_Potion::
	giveitem ITEM_HYPER_POTION
	return

GetItem_Super_Potion::
	giveitem ITEM_SUPER_POTION
	return

GetItem_Full_Heal::
	giveitem ITEM_FULL_HEAL
	return

GetItem_Revive::
	giveitem ITEM_REVIVE
	return

GetItem_Max_Revive::
	giveitem ITEM_MAX_REVIVE
	return

GetItem_Fresh_Water::
	giveitem ITEM_FRESH_WATER
	return

GetItem_Soda_Pop::
	giveitem ITEM_SODA_POP
	return

GetItem_Lemonade::
	giveitem ITEM_LEMONADE
	return

GetItem_Moomoo_Milk::
	giveitem ITEM_MOOMOO_MILK
	return

GetItem_Energy_Powder::
	giveitem ITEM_ENERGY_POWDER
	return

GetItem_Energy_Root::
	giveitem ITEM_ENERGY_ROOT
	return

GetItem_Heal_Powder::
	giveitem ITEM_HEAL_POWDER
	return

GetItem_Revival_Herb::
	giveitem ITEM_REVIVAL_HERB
	return

GetItem_Ether::
	giveitem ITEM_ETHER
	return

GetItem_Max_Ether::
	giveitem ITEM_MAX_ETHER
	return

GetItem_Elixir::
	giveitem ITEM_ELIXIR
	return

GetItem_Max_Elixir::
	giveitem ITEM_MAX_ELIXIR
	return

GetItem_Lava_Cookie::
	giveitem ITEM_LAVA_COOKIE
	return

GetItem_Blue_Flute::
	giveitem ITEM_BLUE_FLUTE
	return

GetItem_Yellow_Flute::
	giveitem ITEM_YELLOW_FLUTE
	return

GetItem_Red_Flute::
	giveitem ITEM_RED_FLUTE
	return

GetItem_Black_Flute::
	giveitem ITEM_BLACK_FLUTE
	return

GetItem_White_Flute::
	giveitem ITEM_WHITE_FLUTE
	return

GetItem_Berry_Juice::
	giveitem ITEM_BERRY_JUICE
	return

GetItem_Sacred_Ash::
	giveitem ITEM_SACRED_ASH
	return

GetItem_Shoal_Salt::
	giveitem ITEM_SHOAL_SALT
	return

GetItem_Shoal_Shell::
	giveitem ITEM_SHOAL_SHELL
	return

GetItem_Red_Shard::
	giveitem ITEM_RED_SHARD
	return

GetItem_Blue_Shard::
	giveitem ITEM_BLUE_SHARD
	return

GetItem_Yellow_Shard::
	giveitem ITEM_YELLOW_SHARD
	return

GetItem_Green_Shard::
	giveitem ITEM_GREEN_SHARD
	return

GetItem_HP_Up::
	giveitem ITEM_HP_UP
	return

GetItem_Protein::
	giveitem ITEM_PROTEIN
	return

GetItem_Iron::
	giveitem ITEM_IRON
	return

GetItem_Carbos::
	giveitem ITEM_CARBOS
	return

GetItem_Calcium::
	giveitem ITEM_CALCIUM
	return

GetItem_Rare_Candy::
	giveitem ITEM_RARE_CANDY
	return

GetItem_PP_Up::
	giveitem ITEM_PP_UP
	return

GetItem_Zinc::
	giveitem ITEM_ZINC
	return

GetItem_PP_Max::
	giveitem ITEM_PP_MAX
	return

GetItem_Guard_Spec::
	giveitem ITEM_GUARD_SPEC
	return

GetItem_Dire_Hit::
	giveitem ITEM_DIRE_HIT
	return

GetItem_X_Attack::
	giveitem ITEM_X_ATTACK
	return

GetItem_X_Defend::
	giveitem ITEM_X_DEFEND
	return

GetItem_X_Speed::
	giveitem ITEM_X_SPEED
	return

GetItem_X_Accuracy::
	giveitem ITEM_X_ACCURACY
	return

GetItem_X_Special::
	giveitem ITEM_X_SPECIAL
	return

GetItem_Poke_Doll::
	giveitem ITEM_POKE_DOLL
	return

GetItem_Fluffy_Tail::
	giveitem ITEM_FLUFFY_TAIL
	return

GetItem_Super_Repel::
	giveitem ITEM_SUPER_REPEL
	return

GetItem_Max_Repel::
	giveitem ITEM_MAX_REPEL
	return

GetItem_Escape_Rope::
	giveitem ITEM_ESCAPE_ROPE
	return

GetItem_Repel::
	giveitem ITEM_REPEL
	return

GetItem_Sun_Stone::
	giveitem ITEM_SUN_STONE
	return

GetItem_Moon_Stone::
	giveitem ITEM_MOON_STONE
	return

GetItem_Fire_Stone::
	giveitem ITEM_FIRE_STONE
	return

GetItem_Thunder_Stone::
	giveitem ITEM_THUNDER_STONE
	return

GetItem_Water_Stone::
	giveitem ITEM_WATER_STONE
	return

GetItem_Leaf_Stone::
	giveitem ITEM_LEAF_STONE
	return

GetItem_Tiny_Mushroom::
	giveitem ITEM_TINY_MUSHROOM
	return

GetItem_Big_Mushroom::
	giveitem ITEM_BIG_MUSHROOM
	return

GetItem_Pearl::
	giveitem ITEM_PEARL
	return

GetItem_Big_Pearl::
	giveitem ITEM_BIG_PEARL
	return

GetItem_Stardust::
	giveitem ITEM_STARDUST
	return

GetItem_Star_Piece::
	giveitem ITEM_STAR_PIECE
	return

GetItem_Nugget::
	giveitem ITEM_NUGGET
	return

GetItem_Heart_Scale::
	giveitem ITEM_HEART_SCALE
	return

GetItem_Orange_Mail::
	giveitem ITEM_ORANGE_MAIL
	return

GetItem_Harbor_Mail::
	giveitem ITEM_HARBOR_MAIL
	return

GetItem_Glitter_Mail::
	giveitem ITEM_GLITTER_MAIL
	return

GetItem_Mech_Mail::
	giveitem ITEM_MECH_MAIL
	return

GetItem_Wood_Mail::
	giveitem ITEM_WOOD_MAIL
	return

GetItem_Wave_Mail::
	giveitem ITEM_WAVE_MAIL
	return

GetItem_Bead_Mail::
	giveitem ITEM_BEAD_MAIL
	return

GetItem_Shadow_Mail::
	giveitem ITEM_SHADOW_MAIL
	return

GetItem_Tropic_Mail::
	giveitem ITEM_TROPIC_MAIL
	return

GetItem_Dream_Mail::
	giveitem ITEM_DREAM_MAIL
	return

GetItem_Fab_Mail::
	giveitem ITEM_FAB_MAIL
	return

GetItem_Retro_Mail::
	giveitem ITEM_RETRO_MAIL
	return

GetItem_Cheri_Berry::
	giveitem ITEM_CHERI_BERRY
	return

GetItem_Chesto_Berry::
	giveitem ITEM_CHESTO_BERRY
	return

GetItem_Pecha_Berry::
	giveitem ITEM_PECHA_BERRY
	return

GetItem_Rawst_Berry::
	giveitem ITEM_RAWST_BERRY
	return

GetItem_Aspear_Berry::
	giveitem ITEM_ASPEAR_BERRY
	return

GetItem_Leppa_Berry::
	giveitem ITEM_LEPPA_BERRY
	return

GetItem_Oran_Berry::
	giveitem ITEM_ORAN_BERRY
	return

GetItem_Persim_Berry::
	giveitem ITEM_PERSIM_BERRY
	return

GetItem_Lum_Berry::
	giveitem ITEM_LUM_BERRY
	return

GetItem_Sitrus_Berry::
	giveitem ITEM_SITRUS_BERRY
	return

GetItem_Figy_Berry::
	giveitem ITEM_FIGY_BERRY
	return

GetItem_Wiki_Berry::
	giveitem ITEM_WIKI_BERRY
	return

GetItem_Mago_Berry::
	giveitem ITEM_MAGO_BERRY
	return

GetItem_Aguav_Berry::
	giveitem ITEM_AGUAV_BERRY
	return

GetItem_Iapapa_Berry::
	giveitem ITEM_IAPAPA_BERRY
	return

GetItem_Razz_Berry::
	giveitem ITEM_RAZZ_BERRY
	return

GetItem_Bluk_Berry::
	giveitem ITEM_BLUK_BERRY
	return

GetItem_Nanab_Berry::
	giveitem ITEM_NANAB_BERRY
	return

GetItem_Wepear_Berry::
	giveitem ITEM_WEPEAR_BERRY
	return

GetItem_Pinap_Berry::
	giveitem ITEM_PINAP_BERRY
	return

GetItem_Pomeg_Berry::
	giveitem ITEM_POMEG_BERRY
	return

GetItem_Kelpsy_Berry::
	giveitem ITEM_KELPSY_BERRY
	return

GetItem_Qualot_Berry::
	giveitem ITEM_QUALOT_BERRY
	return

GetItem_Hondew_Berry::
	giveitem ITEM_HONDEW_BERRY
	return

GetItem_Grepa_Berry::
	giveitem ITEM_GREPA_BERRY
	return

GetItem_Tamato_Berry::
	giveitem ITEM_TAMATO_BERRY
	return

GetItem_Cornn_Berry::
	giveitem ITEM_CORNN_BERRY
	return

GetItem_Magost_Berry::
	giveitem ITEM_MAGOST_BERRY
	return

GetItem_Rabuta_Berry::
	giveitem ITEM_RABUTA_BERRY
	return

GetItem_Nomel_Berry::
	giveitem ITEM_NOMEL_BERRY
	return

GetItem_Spelon_Berry::
	giveitem ITEM_SPELON_BERRY
	return

GetItem_Pamtre_Berry::
	giveitem ITEM_PAMTRE_BERRY
	return

GetItem_Watmel_Berry::
	giveitem ITEM_WATMEL_BERRY
	return

GetItem_Durin_Berry::
	giveitem ITEM_DURIN_BERRY
	return

GetItem_Belue_Berry::
	giveitem ITEM_BELUE_BERRY
	return

GetItem_Liechi_Berry::
	giveitem ITEM_LIECHI_BERRY
	return

GetItem_Ganlon_Berry::
	giveitem ITEM_GANLON_BERRY
	return

GetItem_Salac_Berry::
	giveitem ITEM_SALAC_BERRY
	return

GetItem_Petaya_Berry::
	giveitem ITEM_PETAYA_BERRY
	return

GetItem_Apicot_Berry::
	giveitem ITEM_APICOT_BERRY
	return

GetItem_Lansat_Berry::
	giveitem ITEM_LANSAT_BERRY
	return

GetItem_Starf_Berry::
	giveitem ITEM_STARF_BERRY
	return

GetItem_Enigma_Berry::
	giveitem ITEM_ENIGMA_BERRY
	return

GetItem_Bright_Powder::
	giveitem ITEM_BRIGHT_POWDER
	return

GetItem_White_Herb::
	giveitem ITEM_WHITE_HERB
	return

GetItem_Macho_Brace::
	giveitem ITEM_MACHO_BRACE
	return

GetItem_EXP_SHARE::
	giveitem ITEM_EXP_SHARE
	return

GetItem_Quick_Claw::
	giveitem ITEM_QUICK_CLAW
	return

GetItem_Soothe_Bell::
	giveitem ITEM_SOOTHE_BELL
	return

GetItem_Mental_Herb::
	giveitem ITEM_MENTAL_HERB
	return

GetItem_Choice_Band::
	giveitem ITEM_CHOICE_BAND
	return

GetItem_Kings_Rock::
	giveitem ITEM_KINGS_ROCK
	return

GetItem_Silver_Powder::
	giveitem ITEM_SILVER_POWDER
	return

GetItem_Amulet_Coin::
	giveitem ITEM_AMULET_COIN
	return

GetItem_Cleanse_Tag::
	giveitem ITEM_CLEANSE_TAG
	return

GetItem_Soul_Dew::
	giveitem ITEM_SOUL_DEW
	return

GetItem_Deep_Sea_Scale::
	giveitem ITEM_DEEP_SEA_SCALE
	return

GetItem_Deep_Sea_Tooth::
	giveitem ITEM_DEEP_SEA_TOOTH
	return

GetItem_Smoke_Ball::
	giveitem ITEM_SMOKE_BALL
	return

GetItem_Everstone::
	giveitem ITEM_EVERSTONE
	return

GetItem_Focus_Band::
	giveitem ITEM_FOCUS_BAND
	return

GetItem_Lucky_Egg::
	giveitem ITEM_LUCKY_EGG
	return

GetItem_Scope_Lens::
	giveitem ITEM_SCOPE_LENS
	return

GetItem_Metal_Coat::
	giveitem ITEM_METAL_COAT
	return

GetItem_Leftovers::
	giveitem ITEM_LEFTOVERS
	return

GetItem_Dragon_Scale::
	giveitem ITEM_DRAGON_SCALE
	return

GetItem_Light_Ball::
	giveitem ITEM_LIGHT_BALL
	return

GetItem_Soft_Sand::
	giveitem ITEM_SOFT_SAND
	return

GetItem_Hard_Stone::
	giveitem ITEM_HARD_STONE
	return

GetItem_Miracle_Seed::
	giveitem ITEM_MIRACLE_SEED
	return

GetItem_Black_Glasses::
	giveitem ITEM_BLACK_GLASSES
	return

GetItem_Black_Belt::
	giveitem ITEM_BLACK_BELT
	return

GetItem_Magnet::
	giveitem ITEM_MAGNET
	return

GetItem_Mystic_Water::
	giveitem ITEM_MYSTIC_WATER
	return

GetItem_Sharp_Beak::
	giveitem ITEM_SHARP_BEAK
	return

GetItem_Poison_Barb::
	giveitem ITEM_POISON_BARB
	return

GetItem_Never_Melt_Ice::
	giveitem ITEM_NEVER_MELT_ICE
	return

GetItem_Spell_Tag::
	giveitem ITEM_SPELL_TAG
	return

GetItem_Twisted_Spoon::
	giveitem ITEM_TWISTED_SPOON
	return

GetItem_Charcoal::
	giveitem ITEM_CHARCOAL
	return

GetItem_Dragon_Fang::
	giveitem ITEM_DRAGON_FANG
	return

GetItem_Silk_Scarf::
	giveitem ITEM_SILK_SCARF
	return

GetItem_Up_Grade::
	giveitem ITEM_UP_GRADE
	return

GetItem_Shell_Bell::
	giveitem ITEM_SHELL_BELL
	return

GetItem_Sea_Incense::
	giveitem ITEM_SEA_INCENSE
	return

GetItem_Lax_Incense::
	giveitem ITEM_LAX_INCENSE
	return

GetItem_Lucky_Punch::
	giveitem ITEM_LUCKY_PUNCH
	return

GetItem_Metal_Powder::
	giveitem ITEM_METAL_POWDER
	return

GetItem_Thick_Club::
	giveitem ITEM_THICK_CLUB
	return

GetItem_Stick::
	giveitem ITEM_STICK
	return

GetItem_Red_Scarf::
	giveitem ITEM_RED_SCARF
	return

GetItem_Blue_Scarf::
	giveitem ITEM_BLUE_SCARF
	return

GetItem_Pink_Scarf::
	giveitem ITEM_PINK_SCARF
	return

GetItem_Green_Scarf::
	giveitem ITEM_GREEN_SCARF
	return

GetItem_Yellow_Scarf::
	giveitem ITEM_YELLOW_SCARF
	return


@****KEY ITEMS******


GetItem_Mach_Bike::
	giveitem ITEM_MACH_BIKE
	return

GetItem_Coin_Case::
	giveitem ITEM_COIN_CASE
	return

GetItem_Itemfinder::
	giveitem ITEM_ITEMFINDER
	return

GetItem_Old_Rod::
	checkitem ITEM_OLD_ROD, 1
	compare VAR_RESULT, FALSE
	goto_if_eq giveitem_Old_Rod
	checkitem ITEM_GOOD_ROD, 1
	compare VAR_RESULT, FALSE
	goto_if_eq giveitem_Good_Rod
	giveitem ITEM_SUPER_ROD
	return

GetItem_Good_Rod::
	checkitem ITEM_OLD_ROD, 1
	compare VAR_RESULT, FALSE
	goto_if_eq giveitem_Old_Rod
	checkitem ITEM_GOOD_ROD, 1
	compare VAR_RESULT, FALSE
	goto_if_eq giveitem_Good_Rod
	giveitem ITEM_SUPER_ROD
	return

GetItem_Super_Rod::
	checkitem ITEM_OLD_ROD, 1
	compare VAR_RESULT, FALSE
	goto_if_eq giveitem_Old_Rod
	checkitem ITEM_GOOD_ROD, 1
	compare VAR_RESULT, FALSE
	goto_if_eq giveitem_Good_Rod
	giveitem ITEM_SUPER_ROD
	return

giveitem_Old_Rod::
	giveitem ITEM_OLD_ROD
	return

giveitem_Good_Rod::
	giveitem ITEM_GOOD_ROD
	return

GetItem_SS_TICKET::
	giveitem ITEM_SS_TICKET
	setflag FLAG_RECEIVED_SS_TICKET
	return

GetItem_Contest_Pass::
	giveitem ITEM_CONTEST_PASS
	return

GetItem_Wailmer_Pail::
	giveitem ITEM_WAILMER_PAIL
	return

GetItem_Devon_Goods::
	giveitem ITEM_DEVON_GOODS
	return

GetItem_Soot_Sack::
	giveitem ITEM_SOOT_SACK
	return

GetItem_Basement_Key::
	giveitem ITEM_BASEMENT_KEY
	return

GetItem_Acro_Bike::
	giveitem ITEM_ACRO_BIKE
	return

GetItem_Pokeblock_Case::
	giveitem ITEM_POKEBLOCK_CASE
	return

GetItem_Letter::
	giveitem ITEM_LETTER
	return

GetItem_Eon_Ticket::
	giveitem ITEM_EON_TICKET
	return

GetItem_Red_Orb::
	giveitem ITEM_RED_ORB
	return

GetItem_Blue_Orb::
	giveitem ITEM_BLUE_ORB
	return

GetItem_Scanner::
	giveitem ITEM_SCANNER
	return

GetItem_Go_Goggles::
	giveitem ITEM_GO_GOGGLES
	return

GetItem_Meteorite::
	giveitem ITEM_METEORITE
	return

GetItem_Room_1_Key::
	giveitem ITEM_ROOM_1_KEY
	return

GetItem_Room_2_Key::
	giveitem ITEM_ROOM_2_KEY
	return

GetItem_Room_4_Key::
	giveitem ITEM_ROOM_4_KEY
	return

GetItem_Room_6_Key::
	giveitem ITEM_ROOM_6_KEY
	return

GetItem_Storage_Key::
	giveitem ITEM_STORAGE_KEY
	return

GetItem_Root_Fossil::
	giveitem ITEM_ROOT_FOSSIL
	return

GetItem_Claw_Fossil::
	giveitem ITEM_CLAW_FOSSIL
	return

GetItem_Devon_Scope::
	giveitem ITEM_DEVON_SCOPE
	return

GetItem_Magma_Emblem::
	giveitem ITEM_MAGMA_EMBLEM
	return

GetItem_Powder_Jar::
	giveitem ITEM_POWDER_JAR
	return

GetItem_Old_Sea_Map::
	giveitem ITEM_OLD_SEA_MAP
	return

GetItem_Mystic_Ticket::
	giveitem ITEM_MYSTIC_TICKET
	return

GetItem_Aurora_Ticket::
	giveitem ITEM_AURORA_TICKET
	return

GetItem_TM01::
	giveitem ITEM_TM01
	return

GetItem_TM02::
	giveitem ITEM_TM02
	return

GetItem_TM03::
	giveitem ITEM_TM03
	return

GetItem_TM04::
	giveitem ITEM_TM04
	return

GetItem_TM05::
	giveitem ITEM_TM05
	return

GetItem_TM06::
	giveitem ITEM_TM06
	return

GetItem_TM07::
	giveitem ITEM_TM07
	return

GetItem_TM08::
	giveitem ITEM_TM08
	return

GetItem_TM09::
	giveitem ITEM_TM09
	return

GetItem_TM10::
	giveitem ITEM_TM10
	return

GetItem_TM11::
	giveitem ITEM_TM11
	return

GetItem_TM12::
	giveitem ITEM_TM12
	return

GetItem_TM13::
	giveitem ITEM_TM13
	return

GetItem_TM14::
	giveitem ITEM_TM14
	return

GetItem_TM15::
	giveitem ITEM_TM15
	return

GetItem_TM16::
	giveitem ITEM_TM16
	return

GetItem_TM17::
	giveitem ITEM_TM17
	return

GetItem_TM18::
	giveitem ITEM_TM18
	return

GetItem_TM19::
	giveitem ITEM_TM19
	return

GetItem_TM20::
	giveitem ITEM_TM20
	return

GetItem_TM21::
	giveitem ITEM_TM21
	return

GetItem_TM22::
	giveitem ITEM_TM22
	return

GetItem_TM23::
	giveitem ITEM_TM23
	return

GetItem_TM24::
	giveitem ITEM_TM24
	return

GetItem_TM25::
	giveitem ITEM_TM25
	return

GetItem_TM26::
	giveitem ITEM_TM26
	return

GetItem_TM27::
	giveitem ITEM_TM27
	return

GetItem_TM28::
	giveitem ITEM_TM28
	return

GetItem_TM29::
	giveitem ITEM_TM29
	return

GetItem_TM30::
	giveitem ITEM_TM30
	return

GetItem_TM31::
	giveitem ITEM_TM31
	return

GetItem_TM32::
	giveitem ITEM_TM32
	return

GetItem_TM33::
	giveitem ITEM_TM33
	return

GetItem_TM34::
	giveitem ITEM_TM34
	return

GetItem_TM35::
	giveitem ITEM_TM35
	return

GetItem_TM36::
	giveitem ITEM_TM36
	return

GetItem_TM37::
	giveitem ITEM_TM37
	return

GetItem_TM38::
	giveitem ITEM_TM38
	return

GetItem_TM39::
	giveitem ITEM_TM39
	return

GetItem_TM40::
	giveitem ITEM_TM40
	return

GetItem_TM41::
	giveitem ITEM_TM41
	return

GetItem_TM42::
	giveitem ITEM_TM42
	return

GetItem_TM43::
	giveitem ITEM_TM43
	return

GetItem_TM44::
	giveitem ITEM_TM44
	return

GetItem_TM45::
	giveitem ITEM_TM45
	return

GetItem_TM46::
	giveitem ITEM_TM46
	return

GetItem_TM47::
	giveitem ITEM_TM47
	return

GetItem_TM48::
	giveitem ITEM_TM48
	return

GetItem_TM49::
	giveitem ITEM_TM49
	return

GetItem_TM50::
	giveitem ITEM_TM50
	return

GetItem_HM01::
	giveitem ITEM_HM01
	return

GetItem_HM02::
	giveitem ITEM_HM02
	return

GetItem_HM03::
	giveitem ITEM_HM03
	return

GetItem_HM04::
	giveitem ITEM_HM04
	return

GetItem_HM05::
	giveitem ITEM_HM05
	return

GetItem_HM06::
	giveitem ITEM_HM06
	return

GetItem_HM07::
	giveitem ITEM_HM07
	return

GetItem_HM08::
	giveitem ITEM_HM08
	return

Add_Var_Petalburg_Gym::
	addvar VAR_PETALBURG_GYM_STATE, 1
	return

GetItem_Stone_Badge::
	message RustboroCity_Gym_Text_ReceivedStoneBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare	
	setflag FLAG_BADGE01_GET
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_lt Add_Var_Petalburg_Gym
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_eq Common_EventScript_ReadyPetalburgGymForBattle
	return

GetItem_Knuckle_Badge::
	message DewfordTown_Gym_Text_ReceivedKnuckleBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare	
	setflag FLAG_BADGE02_GET
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_lt Add_Var_Petalburg_Gym
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_eq Common_EventScript_ReadyPetalburgGymForBattle
	return

GetItem_Dynamo_Badge::
	message MauvilleCity_Gym_Text_ReceivedDynamoBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare	
	setflag FLAG_BADGE03_GET
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_lt Add_Var_Petalburg_Gym
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_eq Common_EventScript_ReadyPetalburgGymForBattle
	return

GetItem_Heat_Badge::
	message LavaridgeTown_Gym_1F_Text_ReceivedHeatBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare	
	setflag FLAG_BADGE04_GET
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_lt Add_Var_Petalburg_Gym
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_eq Common_EventScript_ReadyPetalburgGymForBattle
	return

GetItem_Balance_Badge::
	message PetalburgCity_Gym_Text_ReceivedBalanceBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare
	setflag FLAG_BADGE05_GET
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_lt Add_Var_Petalburg_Gym
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_eq Common_EventScript_ReadyPetalburgGymForBattle
	return

GetItem_Feather_Badge::	
	message FortreeCity_Gym_Text_ReceivedFeatherBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare
	setflag FLAG_BADGE06_GET
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_lt Add_Var_Petalburg_Gym
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_eq Common_EventScript_ReadyPetalburgGymForBattle
	return

GetItem_Mind_Badge::
	message MossdeepCity_Gym_Text_ReceivedMindBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare
	setflag FLAG_BADGE07_GET
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_lt Add_Var_Petalburg_Gym
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_eq Common_EventScript_ReadyPetalburgGymForBattle
	return

GetItem_Rain_Badge::
	message SootopolisCity_Gym_1F_Text_ReceivedRainBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare
	setflag FLAG_BADGE08_GET
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_lt Add_Var_Petalburg_Gym
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_eq Common_EventScript_ReadyPetalburgGymForBattle
	return

GetItem_Pokedex::
	goto_if_set FLAG_SYS_POKEDEX_GET, EventScript_Give_National_Dex
	playfanfare MUS_OBTAIN_ITEM
	message LittlerootTown_ProfessorBirchsLab_Text_ReceivedPokedex
	waitfanfare
	setflag FLAG_SYS_POKEDEX_GET
	special SetUnlockedPokedexFlags
	return

GetItem_National_Dex::
	goto_if_set FLAG_SYS_POKEDEX_GET, EventScript_Give_National_Dex
	playfanfare MUS_OBTAIN_ITEM
	message LittlerootTown_ProfessorBirchsLab_Text_ReceivedPokedex
	waitfanfare
	setflag FLAG_SYS_POKEDEX_GET
	special SetUnlockedPokedexFlags
	return

EventScript_Give_National_Dex::
	playfanfare MUS_OBTAIN_ITEM
	message LittlerootTown_ProfessorBirchsLab_Text_PokedexUpgradedToNational
	waitmessage
	waitfanfare
	setflag FLAG_SYS_NATIONAL_DEX
	special EnableNationalPokedex
	return

GetItem_RunningShoes::
	playfanfare MUS_OBTAIN_ITEM
	message LittlerootTown_Text_SwitchShoesWithRunningShoes
	waitfanfare
	setflag FLAG_SYS_B_DASH
	return

GetItem_PokeNav::
	playfanfare MUS_OBTAIN_ITEM
	message RustboroCity_DevonCorp_3F_Text_ReceivedPokenav
	waitfanfare
	setflag FLAG_SYS_POKENAV_GET
	return

GetItem_Frontier_Pass::
	playfanfare MUS_OBTAIN_ITEM
	message BattleFrontier_ReceptionGate_Text_ObtainedFrontierPass
	waitfanfare
	waitmessage
	msgbox BattleFrontier_ReceptionGate_Text_PlacedTrainerCardInFrontierPass, MSGBOX_DEFAULT
	setflag FLAG_SYS_FRONTIER_PASS
	return

GetItem_Ability_Silver::
	setvar VAR_FRONTIER_FACILITY, 0
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattleTowerBattleRoom_Text_ReceivedAbilitySymbol	
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Ability_Gold::
	setvar VAR_FRONTIER_FACILITY, 0
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattleTowerBattleRoom_Text_AbilitySymbolTookGoldenShine
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Tactics_Silver::
	setvar VAR_FRONTIER_FACILITY, 1
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattleDomeBattleRoom_Text_ReceivedTacticsSymbol
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Tactics_Gold::
	setvar VAR_FRONTIER_FACILITY, 1
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattleDomeBattleRoom_Text_TacticsSymbolTookGoldenShine
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Spirit_Silver::
	setvar VAR_FRONTIER_FACILITY, 2
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattlePalaceBattleRoom_Text_ReceivedSpiritsSymbol
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Spirit_Gold::
	setvar VAR_FRONTIER_FACILITY, 2
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattlePalaceBattleRoom_Text_SpiritsSymbolTookGoldenShine
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Guts_Silver::
	setvar VAR_FRONTIER_FACILITY, 3
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattleArenaBattleRoom_Text_ReceivedGutsSymbol	
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Guts_Gold::
	setvar VAR_FRONTIER_FACILITY, 3
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattleArenaBattleRoom_Text_GutsSymbolTookGoldenShine
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Knowledge_Silver::
	setvar VAR_FRONTIER_FACILITY, 4
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattleFactoryBattleRoom_Text_ReceivedKnowledgeSymbol
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Knowledge_Gold::
	setvar VAR_FRONTIER_FACILITY, 4
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattleFactoryBattleRoom_Text_KnowledgeSymbolTookGoldenShine
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Luck_Silver::
	setvar VAR_FRONTIER_FACILITY, 5
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattlePikeRoomNormal_Text_ReceivedLuckSymbol	
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Luck_Gold::
	setvar VAR_FRONTIER_FACILITY, 5
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattlePikeRoomNormal_Text_LuckSymbolTookGoldenShine
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Brave_Silver::
	setvar VAR_FRONTIER_FACILITY, 6 
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattlePyramidTop_Text_ReceivedBraveSymbol
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Brave_Gold::
	setvar VAR_FRONTIER_FACILITY, 6 
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattlePyramidTop_Text_BraveSymbolTookGoldenShine
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

























