SCR_REMOVE::
	removeobject VAR_LAST_TALKED
	return

Route102_EventScript_ItemPotion:: @ 8290CD8
	playse SE_SELECT
	waitse
	call GetItem_Potion
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route103_EventScript_ItemGuardSpec:: @ 8290CE5
	playse SE_SELECT
	waitse
	call GetItem_Guard_Spec
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route103_EventScript_ItemPPUp:: @ 8290CF2
	playse SE_SELECT
	waitse
	call GetItem_PP_Up
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route104_EventScript_ItemPPUp:: @ 8290CFF
	playse SE_SELECT
	waitse
	call GetItem_PP_Up
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route104_EventScript_ItemPokeBall:: @ 8290D0C
	playse SE_SELECT
	waitse
	call GetItem_Poke_Ball
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route104_EventScript_ItemXAccuracy:: @ 8290D19
	playse SE_SELECT
	waitse
	call GetItem_X_Accuracy
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route104_EventScript_ItemPotion:: @ 8290D26
	playse SE_SELECT
	waitse
	call GetItem_Potion
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route105_EventScript_ItemIron:: @ 8290D33
	playse SE_SELECT
	waitse
	call GetItem_Iron
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route106_EventScript_ItemProtein:: @ 8290D40
	playse SE_SELECT
	waitse
	call GetItem_Protein
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route108_EventScript_ItemStarPiece:: @ 8290D4D
	playse SE_SELECT
	waitse
	call GetItem_Star_Piece
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route109_EventScript_ItemPPUp:: @ 8290D5A
	playse SE_SELECT
	waitse
	call GetItem_PP_Up
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route109_EventScript_ItemPotion:: @ 8290D67
	playse SE_SELECT
	waitse
	call GetItem_Potion
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route110_EventScript_ItemRareCandy:: @ 8290D74
	playse SE_SELECT
	waitse
	call GetItem_Rare_Candy
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route110_EventScript_ItemDireHit:: @ 8290D81
	playse SE_SELECT
	waitse
	call GetItem_Dire_Hit
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route110_EventScript_ItemElixir:: @ 8290D8E
	playse SE_SELECT
	waitse
	call GetItem_Elixir
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route111_EventScript_ItemTM37:: @ 8290D9B
	playse SE_SELECT
	waitse
	call GetItem_TM37
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route111_EventScript_ItemStardust:: @ 8290DA8
	playse SE_SELECT
	waitse
	call GetItem_Stardust
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route111_EventScript_ItemHPUp:: @ 8290DB5
	playse SE_SELECT
	waitse
	call GetItem_HP_Up
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route111_EventScript_ItemElixir:: @ 8290DC2
	playse SE_SELECT
	waitse
	call GetItem_Elixir
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route112_EventScript_ItemNugget:: @ 8290DCF
	playse SE_SELECT
	waitse
	call GetItem_Nugget
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route113_EventScript_ItemMaxEther:: @ 8290DDC
	playse SE_SELECT
	waitse
	call GetItem_Max_Ether
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route113_EventScript_ItemSuperRepel:: @ 8290DE9
	playse SE_SELECT
	waitse
	call GetItem_Super_Repel
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route113_EventScript_ItemHyperPotion:: @ 8290DF6
	playse SE_SELECT
	waitse
	call GetItem_Hyper_Potion
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route114_EventScript_ItemRareCandy:: @ 8290E03
	playse SE_SELECT
	waitse
	call GetItem_Rare_Candy
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route114_EventScript_ItemProtein:: @ 8290E10
	playse SE_SELECT
	waitse
	call GetItem_Protein
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route114_EventScript_ItemEnergyPowder:: @ 8290E1D
	playse SE_SELECT
	waitse
	call GetItem_Energy_Powder
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route115_EventScript_ItemSuperPotion:: @ 8290E2A
	playse SE_SELECT
	waitse
	call GetItem_Super_Potion
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route115_EventScript_ItemTM01:: @ 8290E37
	playse SE_SELECT
	waitse
	call GetItem_TM01
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route115_EventScript_ItemIron:: @ 8290E44
	playse SE_SELECT
	waitse
	call GetItem_Iron
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route115_EventScript_ItemGreatBall:: @ 8290E51
	playse SE_SELECT
	waitse
	call GetItem_Great_Ball
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route115_EventScript_ItemHealPowder:: @ 8290E5E
	playse SE_SELECT
	waitse
	call GetItem_Heal_Powder
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route115_EventScript_ItemPPUp:: @ 8290E6B
	playse SE_SELECT
	waitse
	call GetItem_PP_Up
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route116_EventScript_ItemXSpecial:: @ 8290E78
	playse SE_SELECT
	waitse
	call GetItem_X_Special
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route116_EventScript_ItemEther:: @ 8290E85
	playse SE_SELECT
	waitse
	call GetItem_Ether
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route116_EventScript_ItemRepel:: @ 8290E92
	playse SE_SELECT
	waitse
	call GetItem_Repel
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route116_EventScript_ItemHPUp:: @ 8290E9F
	playse SE_SELECT
	waitse
	call GetItem_HP_Up
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route116_EventScript_ItemPotion:: @ 8290EAC
	playse SE_SELECT
	waitse
	call GetItem_Potion
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route117_EventScript_ItemGreatBall:: @ 8290EB9
	playse SE_SELECT
	waitse
	call GetItem_Great_Ball
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route117_EventScript_ItemRevive:: @ 8290EC6
	playse SE_SELECT
	waitse
	call GetItem_Revive
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route118_EventScript_ItemHyperPotion:: @ 8290ED3
	playse SE_SELECT
	waitse
	call GetItem_Hyper_Potion
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route119_EventScript_ItemSuperRepel:: @ 8290EE0
	playse SE_SELECT
	waitse
	call GetItem_Super_Repel
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route119_EventScript_ItemZinc:: @ 8290EED
	playse SE_SELECT
	waitse
	call GetItem_Zinc
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route119_EventScript_ItemElixir:: @ 8290EFA	
	playse SE_SELECT
	waitse
	call GetItem_Elixir
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route119_EventScript_ItemLeafStone:: @ 8290F07
	playse SE_SELECT
	waitse
	call GetItem_Leaf_Stone
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route119_EventScript_ItemRareCandy:: @ 8290F14
	playse SE_SELECT
	waitse
	call GetItem_Rare_Candy
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route119_EventScript_ItemHyperPotion:: @ 8290F21
	playse SE_SELECT
	waitse
	call GetItem_Hyper_Potion
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route119_EventScript_ItemHyperPotion2:: @ 8290F2E
	playse SE_SELECT
	waitse
	call GetItem_Hyper_Potion
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route119_EventScript_ItemElixir2:: @ 8290F3B
	playse SE_SELECT
	waitse
	call GetItem_Elixir
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route120_EventScript_ItemNugget:: @ 8290F48
	playse SE_SELECT
	waitse
	call GetItem_Nugget
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route120_EventScript_ItemFullHeal:: @ 8290F55
	playse SE_SELECT
	waitse
	call GetItem_Full_Heal
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route120_EventScript_ItemHyperPotion:: @ 8290F62
	playse SE_SELECT
	waitse
	call GetItem_Hyper_Potion
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route120_EventScript_ItemNestBall:: @ 8290F6F
	playse SE_SELECT
	waitse
	call GetItem_Nest_Ball
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route120_EventScript_ItemRevive:: @ 8290F7C
	playse SE_SELECT
	waitse
	call GetItem_Revive
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route121_EventScript_ItemCarbos:: @ 8290F89
	playse SE_SELECT
	waitse
	call GetItem_Carbos
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route121_EventScript_ItemRevive:: @ 8290F96
	playse SE_SELECT
	waitse
	call GetItem_Revive
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route121_EventScript_ItemZinc:: @ 8290FA3
	playse SE_SELECT
	waitse
	call GetItem_Zinc
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route123_EventScript_ItemCalcium:: @ 8290FB0
	playse SE_SELECT
	waitse
	call GetItem_Calcium
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route123_EventScript_ItemUltraBall:: @ 8290FBD
	playse SE_SELECT
	waitse
	call GetItem_Ultra_Ball
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route123_EventScript_ItemElixir:: @ 8290FCA
	playse SE_SELECT
	waitse
	call GetItem_Elixir
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route123_EventScript_ItemPPUp:: @ 8290FD7
	playse SE_SELECT
	waitse
	call GetItem_PP_Up
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route123_EventScript_ItemRevivalHerb:: @ 8290FE4
	playse SE_SELECT
	waitse
	call GetItem_Revival_Herb
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route124_EventScript_ItemRedShard:: @ 8290FF1
	playse SE_SELECT
	waitse
	call GetItem_Red_Shard
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route124_EventScript_ItemBlueShard:: @ 8290FFE
	playse SE_SELECT
	waitse
	call GetItem_Blue_Shard
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route124_EventScript_ItemYellowShard:: @ 829100B
	playse SE_SELECT
	waitse
	call GetItem_Yellow_Shard
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route125_EventScript_ItemBigPearl:: @ 8291018
	playse SE_SELECT
	waitse
	call GetItem_Big_Pearl
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route126_EventScript_ItemGreenShard:: @ 8291025
	playse SE_SELECT
	waitse
	call GetItem_Green_Shard
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route127_EventScript_ItemZinc:: @ 8291032
	playse SE_SELECT
	waitse
	call GetItem_Zinc
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route127_EventScript_ItemCarbos:: @ 829103F
	playse SE_SELECT
	waitse
	call GetItem_Carbos
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route127_EventScript_ItemRareCandy:: @ 829104C
	playse SE_SELECT
	waitse
	call GetItem_Rare_Candy
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route132_EventScript_ItemRareCandy:: @ 8291059
	playse SE_SELECT
	waitse
	call GetItem_Rare_Candy
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route132_EventScript_ItemProtein:: @ 8291066
	playse SE_SELECT
	waitse
	call GetItem_Protein
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route133_EventScript_ItemBigPearl:: @ 8291073
	playse SE_SELECT
	waitse
	call GetItem_Big_Pearl
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route133_EventScript_ItemStarPiece:: @ 8291080
	playse SE_SELECT
	waitse
	call GetItem_Star_Piece
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route133_EventScript_ItemMaxRevive:: @ 829108D
	playse SE_SELECT
	waitse
	call GetItem_Max_Revive
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route134_EventScript_ItemCarbos:: @ 829109A
	playse SE_SELECT
	waitse
	call GetItem_Carbos
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route134_EventScript_ItemStarPiece:: @ 82910A7
	playse SE_SELECT
	waitse
	call GetItem_Star_Piece
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

PetalburgCity_EventScript_ItemMaxRevive:: @ 82910B4
	playse SE_SELECT
	waitse
	call GetItem_Max_Revive
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

PetalburgCity_EventScript_ItemEther:: @ 82910C1
	playse SE_SELECT
	waitse
	call GetItem_Ether
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

MauvilleCity_EventScript_ItemXSpeed:: @ 82910CE
	playse SE_SELECT
	waitse
	call GetItem_X_Speed
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

RustboroCity_EventScript_ItemXDefend:: @ 82910DB
	playse SE_SELECT
	waitse
	call GetItem_X_Defend
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

LilycoveCity_EventScript_ItemMaxRepel:: @ 82910E8
	playse SE_SELECT
	waitse
	call GetItem_Max_Repel
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

MossdeepCity_EventScript_ItemNetBall:: @ 82910F5
	playse SE_SELECT
	waitse
	call GetItem_Net_Ball
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

PetalburgWoods_EventScript_ItemXAttack:: @ 8291102
	playse SE_SELECT
	waitse
	call GetItem_X_Attack
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

PetalburgWoods_EventScript_ItemGreatBall:: @ 829110F
	playse SE_SELECT
	waitse
	call GetItem_Great_Ball
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

PetalburgWoods_EventScript_ItemEther:: @ 829111C
	playse SE_SELECT
	waitse
	call GetItem_Ether
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

PetalburgWoods_EventScript_ItemParalyzeHeal:: @ 8291129
	playse SE_SELECT
	waitse
	call GetItem_Paralyze_Heal
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

RusturfTunnel_EventScript_ItemPokeBall:: @ 8291136
	playse SE_SELECT
	waitse
	call GetItem_Poke_Ball
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

RusturfTunnel_EventScript_ItemMaxEther:: @ 8291143
	playse SE_SELECT
	waitse
	call GetItem_Max_Ether
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

GraniteCave_1F_EventScript_ItemEscapeRope:: @ 8291150
	playse SE_SELECT
	waitse
	call GetItem_Escape_Rope
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

GraniteCave_B1F_EventScript_ItemPokeBall:: @ 829115D
	playse SE_SELECT
	waitse
	call GetItem_Poke_Ball
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

GraniteCave_B2F_EventScript_ItemRepel:: @ 829116A
	playse SE_SELECT
	waitse
	call GetItem_Repel
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

GraniteCave_B2F_EventScript_ItemRareCandy:: @ 8291177
	playse SE_SELECT
	waitse
	call GetItem_Rare_Candy
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

JaggedPass_EventScript_ItemBurnHeal:: @ 8291184
	playse SE_SELECT
	waitse
	call GetItem_Burn_Heal
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

FieryPath_EventScript_ItemFireStone:: @ 8291191
	playse SE_SELECT
	waitse
	call GetItem_Fire_Stone
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

FieryPath_EventScript_ItemTM06:: @ 829119E
	playse SE_SELECT
	waitse
	call GetItem_TM06
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

MeteorFalls_1F_1R_EventScript_ItemTM23:: @ 82911AB
	playse SE_SELECT
	waitse
	call GetItem_TM23
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

MeteorFalls_1F_1R_EventScript_ItemFullHeal:: @ 82911B8
	playse SE_SELECT
	waitse
	call GetItem_Full_Heal
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

MeteorFalls_1F_1R_EventScript_ItemMoonStone:: @ 82911C5
	playse SE_SELECT
	waitse
	call GetItem_Moon_Stone
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

MeteorFalls_1F_1R_EventScript_ItemPPUP:: @ 82911D2
	playse SE_SELECT
	waitse
	call GetItem_PP_Up
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

MeteorFalls_B1F_2R_EventScript_ItemTM02:: @ 82911DF
	playse SE_SELECT
	waitse
	call GetItem_TM02
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

NewMauville_Inside_EventScript_ItemUltraBall:: @ 82911EC
	playse SE_SELECT
	waitse
	call GetItem_Ultra_Ball
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

NewMauville_Inside_EventScript_ItemEscapeRope:: @ 82911F9
	playse SE_SELECT
	waitse
	call GetItem_Escape_Rope
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

NewMauville_Inside_EventScript_ItemThunderStone:: @ 8291206
	playse SE_SELECT
	waitse
	call GetItem_Thunder_Stone
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

NewMauville_Inside_EventScript_ItemFullHeal:: @ 8291213
	playse SE_SELECT
	waitse
	call GetItem_Full_Heal
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

NewMauville_Inside_EventScript_ItemParalyzeHeal:: @ 8291220
	playse SE_SELECT
	waitse
	call GetItem_Paralyze_Heal
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

AbandonedShip_Rooms_1F_EventScript_ItemHarborMail:: @ 829122D
	playse SE_SELECT
	waitse
	call GetItem_Harbor_Mail
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

AbandonedShip_Rooms_B1F_EventScript_ItemEscapeRope:: @ 829123A
	playse SE_SELECT
	waitse
	call GetItem_Escape_Rope
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

AbandonedShip_Rooms2_B1F_EventScript_ItemDiveBall:: @ 8291247
	playse SE_SELECT
	waitse
	call GetItem_Dive_Ball
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

AbandonedShip_Room_B1F_EventScript_ItemTM13:: @ 8291254
	playse SE_SELECT
	waitse
	call GetItem_TM13
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

AbandonedShip_Rooms2_1F_EventScript_ItemRevive:: @ 8291261
	playse SE_SELECT
	waitse
	call GetItem_Revive
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

AbandonedShip_CaptainsOffice_EventScript_ItemStorageKey:: @ 829126E
	playse SE_SELECT
	waitse
	call GetItem_Storage_Key
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemLuxuryBall:: @ 829127B
	playse SE_SELECT
	waitse
	call GetItem_Luxury_Ball
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemScanner:: @ 8291288
	playse SE_SELECT
	waitse
	call GetItem_Scanner
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemWaterStone:: @ 8291295
	playse SE_SELECT
	waitse
	call GetItem_Water_Stone
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemTM18:: @ 82912A2
	playse SE_SELECT
	waitse
	call GetItem_TM18
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

ScorchedSlab_EventScript_ItemTM11:: @ 82912AF
	playse SE_SELECT
	waitse
	call GetItem_TM11
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

SafariZone_Northwest_EventScript_ItemTM22:: @ 82912BC
	playse SE_SELECT
	waitse
	call GetItem_TM22
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

SafariZone_North_EventScript_ItemCalcium:: @ 82912C9
	playse SE_SELECT
	waitse
	call GetItem_Calcium
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

SafariZone_Southwest_EventScript_ItemMaxRevive:: @ 82912D6
	playse SE_SELECT
	waitse
	call GetItem_Max_Revive
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

SafariZone_Northeast_EventScript_ItemNugget:: @ 82912E3
	playse SE_SELECT
	waitse
	call GetItem_Nugget
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

SafariZone_Southeast_EventScript_ItemBigPearl:: @ 82912F0
	playse SE_SELECT
	waitse
	call GetItem_Big_Pearl
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

MtPyre_2F_EventScript_ItemUltraBall:: @ 82912FD
	playse SE_SELECT
	waitse
	call GetItem_Ultra_Ball
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

MtPyre_3F_EventScript_ItemSuperRepel:: @ 829130A
	playse SE_SELECT
	waitse
	call GetItem_Super_Repel
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

MtPyre_4F_EventScript_ItemSeaIncense:: @ 8291317
	playse SE_SELECT
	waitse
	call GetItem_Sea_Incense
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

MtPyre_5F_EventScript_ItemLaxIncense:: @ 8291324
	playse SE_SELECT
	waitse
	call GetItem_Lax_Incense
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

MtPyre_6F_EventScript_ItemTM30:: @ 8291331
	playse SE_SELECT
	waitse
	call GetItem_TM30
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

MtPyre_Exterior_EventScript_ItemMaxPotion:: @ 829133E
	playse SE_SELECT
	waitse
	call GetItem_Max_Potion
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

MtPyre_Exterior_EventScript_ItemTM48:: @ 829134B
	playse SE_SELECT
	waitse
	call GetItem_TM48
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

AquaHideout_B1F_EventScript_ItemMasterBall:: @ 8291358
	playse SE_SELECT
	waitse
	call GetItem_Master_Ball
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

AquaHideout_B1F_EventScript_ItemNugget:: @ 8291365
	playse SE_SELECT
	waitse
	call GetItem_Nugget
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

AquaHideout_B1F_EventScript_ItemMaxElixir:: @ 8291372
	playse SE_SELECT
	waitse
	call GetItem_Max_Elixir
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

AquaHideout_B2F_EventScript_ItemNestBall:: @ 829137F
	playse SE_SELECT
	waitse
	call GetItem_Nest_Ball
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

AquaHideout_B2F_EventScript_ItemMasterBall:: @ 829138C
	finditem ITEM_MASTER_BALL      // Unused
	end

Route119_EventScript_ItemNugget:: @ 8291399
	playse SE_SELECT
	waitse
	call GetItem_Nugget
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route119_EventScript_ItemMaxElixir:: @ 82913A6
	playse SE_SELECT
	waitse
	call GetItem_Elixir
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route119_EventScript_ItemNestBall:: @ 82913B3
	playse SE_SELECT
	waitse
	call GetItem_Nest_Ball
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

ShoalCave_LowTideEntranceRoom_EventScript_ItemBigPearl:: @ 82913C0
	playse SE_SELECT
	waitse
	call GetItem_Big_Pearl
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

ShoalCave_LowTideInnerRoom_EventScript_ItemRareCandy:: @ 82913CD
	playse SE_SELECT
	waitse
	call GetItem_Rare_Candy
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

ShoalCave_LowTideStairsRoom_EventScript_ItemIceHeal:: @ 82913DA
	playse SE_SELECT
	waitse
	call GetItem_Ice_Heal
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

ShoalCave_LowTideIceRoom_EventScript_ItemTM07:: @ 82913E7
	playse SE_SELECT
	waitse
	call GetItem_TM07
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

ShoalCave_LowTideIceRoom_EventScript_ItemNeverMeltIce:: @ 82913F4
	playse SE_SELECT
	waitse
	call GetItem_Never_Melt_Ice
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

SeafloorCavern_Room9_EventScript_ItemTM26:: @ 8291401
	playse SE_SELECT
	waitse
	call GetItem_TM26
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route110_TrickHousePuzzle1_EventScript_ItemOrangeMail:: @ 829140E
	playse SE_SELECT
	waitse
	call GetItem_Orange_Mail
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route110_TrickHousePuzzle2_EventScript_ItemHarborMail:: @ 829141B
	playse SE_SELECT
	waitse
	call GetItem_Harbor_Mail
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route110_TrickHousePuzzle2_EventScript_ItemWaveMail:: @ 8291428
	playse SE_SELECT
	waitse
	call GetItem_Wave_Mail
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route110_TrickHousePuzzle3_EventScript_ItemShadowMail:: @ 8291435
	playse SE_SELECT
	waitse
	call GetItem_Shadow_Mail
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route110_TrickHousePuzzle3_EventScript_ItemWoodMail:: @ 8291442
	playse SE_SELECT
	waitse
	call GetItem_Wood_Mail
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route110_TrickHousePuzzle4_EventScript_ItemMechMail:: @ 829144F
	playse SE_SELECT
	waitse
	call GetItem_Mech_Mail
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route110_TrickHousePuzzle6_EventScript_ItemGlitterMail:: @ 829145C
	playse SE_SELECT
	waitse
	call GetItem_Glitter_Mail
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route110_TrickHousePuzzle7_EventScript_ItemTropicMail:: @ 8291469
	playse SE_SELECT
	waitse
	call GetItem_Tropic_Mail
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

Route110_TrickHousePuzzle8_EventScript_ItemBeadMail:: @ 8291476
	playse SE_SELECT
	waitse
	call GetItem_Bead_Mail
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

VictoryRoad_1F_EventScript_ItemMaxElixir:: @ 8291483
	playse SE_SELECT
	waitse
	call GetItem_Max_Elixir
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

VictoryRoad_1F_EventScript_ItemPPUp:: @ 8291490
	playse SE_SELECT
	waitse
	call GetItem_PP_Up
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

VictoryRoad_B1F_EventScript_ItemTM29:: @ 829149D
	playse SE_SELECT
	waitse
	call GetItem_TM29
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

VictoryRoad_B1F_EventScript_ItemFullRestore:: @ 82914AA
	playse SE_SELECT
	waitse
	call GetItem_Full_Restore
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

VictoryRoad_B2F_EventScript_ItemFullHeal:: @ 82914B7
	playse SE_SELECT
	waitse
	call GetItem_Full_Heal
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

ArtisanCave_B1F_EventScript_ItemHPUp:: @ 82914C4
	playse SE_SELECT
	waitse
	call GetItem_HP_Up
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

ArtisanCave_1F_EventScript_ItemCarbos:: @ 82914D1
	playse SE_SELECT
	waitse
	call GetItem_Carbos
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

MagmaHideout_1F_EventScript_ItemRareCandy:: @ 82914DE
	playse SE_SELECT
	waitse
	call GetItem_Rare_Candy
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

MagmaHideout_2F_2R_EventScript_MaxElixir:: @ 82914EB
	playse SE_SELECT
	waitse
	call GetItem_Max_Elixir
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

MagmaHideout_2F_2R_EventScript_ItemFullRestore:: @ 82914F8
	playse SE_SELECT
	waitse
	call GetItem_Full_Restore
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

MagmaHideout_3F_1R_EventScript_ItemNugget:: @ 8291505
	playse SE_SELECT
	waitse
	call GetItem_Nugget
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

MagmaHideout_3F_2R_EventScript_ItemPPMax:: @ 8291512
	playse SE_SELECT
	waitse
	call GetItem_PP_Max
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

MagmaHideout_4F_EventScript_MaxRevive:: @ 829151F
	playse SE_SELECT
	waitse
	call GetItem_Revive
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

MagmaHideout_3F_3R_EventScript_ItemEscapeRope:: @ 829152C
	playse SE_SELECT
	waitse
	call GetItem_Escape_Rope
	compare VAR_0x8007, 1
	call_if_eq SCR_REMOVE
	closemessage
	end

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@				@
@         ITEM SCRIPTS		@		
@				@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

GetItem_Master_Ball::
	giveitem ITEM_MASTER_BALL
	return

GetItem_Ultra_Ball::
	giveitem ITEM_ULTRA_BALL
	return

GetItem_Great_Ball::
	giveitem ITEM_GREAT_BALL
	return

GetItem_Poke_Ball::
	giveitem ITEM_POKE_BALL
	return

GetItem_5_Poke_Balls::
	giveitem ITEM_POKE_BALL, 5
	return

GetItem_Safari_Ball::
	giveitem ITEM_SAFARI_BALL
	return

GetItem_Net_Ball::
	giveitem ITEM_NET_BALL
	return

GetItem_Dive_Ball::
	giveitem ITEM_DIVE_BALL
	return

GetItem_Nest_Ball::
	giveitem ITEM_NEST_BALL
	return

GetItem_Repeat_Ball::
	giveitem ITEM_REPEAT_BALL
	return

GetItem_Timer_Ball::
	giveitem ITEM_TIMER_BALL
	return

GetItem_Luxury_Ball::
	giveitem ITEM_LUXURY_BALL
	return

GetItem_Premier_Ball::
	giveitem ITEM_PREMIER_BALL
	return

GetItem_Potion::
	giveitem ITEM_POTION
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Antidote::
	giveitem ITEM_ANTIDOTE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Burn_Heal::
	giveitem ITEM_BURN_HEAL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Ice_Heal::
	giveitem ITEM_ICE_HEAL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Awakening::
	giveitem ITEM_AWAKENING
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Paralyze_Heal::
	giveitem ITEM_PARALYZE_HEAL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Full_Restore::
	giveitem ITEM_FULL_RESTORE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Max_Potion::
	giveitem ITEM_MAX_POTION
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Hyper_Potion::
	giveitem ITEM_HYPER_POTION
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Super_Potion::
	giveitem ITEM_SUPER_POTION
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Full_Heal::
	giveitem ITEM_FULL_HEAL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Revive::
	giveitem ITEM_REVIVE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Max_Revive::
	giveitem ITEM_MAX_REVIVE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Fresh_Water::
	giveitem ITEM_FRESH_WATER
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Soda_Pop::
	giveitem ITEM_SODA_POP
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Lemonade::
	giveitem ITEM_LEMONADE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Moomoo_Milk::
	giveitem ITEM_MOOMOO_MILK
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Energy_Powder::
	giveitem ITEM_ENERGY_POWDER
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Energy_Root::
	giveitem ITEM_ENERGY_ROOT
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Heal_Powder::
	giveitem ITEM_HEAL_POWDER
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Revival_Herb::
	giveitem ITEM_REVIVAL_HERB
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Ether::
	giveitem ITEM_ETHER
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Max_Ether::
	giveitem ITEM_MAX_ETHER
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Elixir::
	giveitem ITEM_ELIXIR
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Max_Elixir::
	giveitem ITEM_MAX_ELIXIR
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Lava_Cookie::
	giveitem ITEM_LAVA_COOKIE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Blue_Flute::
	giveitem ITEM_BLUE_FLUTE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Yellow_Flute::
	giveitem ITEM_YELLOW_FLUTE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Red_Flute::
	giveitem ITEM_RED_FLUTE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Black_Flute::
	giveitem ITEM_BLACK_FLUTE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_White_Flute::
	giveitem ITEM_WHITE_FLUTE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Berry_Juice::
	giveitem ITEM_BERRY_JUICE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Sacred_Ash::
	giveitem ITEM_SACRED_ASH
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Shoal_Salt::
	giveitem ITEM_SHOAL_SALT
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Shoal_Shell::
	giveitem ITEM_SHOAL_SHELL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Red_Shard::
	giveitem ITEM_RED_SHARD
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Blue_Shard::
	giveitem ITEM_BLUE_SHARD
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Yellow_Shard::
	giveitem ITEM_YELLOW_SHARD
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Green_Shard::
	giveitem ITEM_GREEN_SHARD
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_HP_Up::
	giveitem ITEM_HP_UP
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Protein::
	giveitem ITEM_PROTEIN
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Iron::
	giveitem ITEM_IRON
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Carbos::
	giveitem ITEM_CARBOS
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Calcium::
	giveitem ITEM_CALCIUM
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Rare_Candy::
	giveitem ITEM_RARE_CANDY
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_PP_Up::
	giveitem ITEM_PP_UP
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Zinc::
	giveitem ITEM_ZINC
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_PP_Max::
	giveitem ITEM_PP_MAX
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Guard_Spec::
	giveitem ITEM_GUARD_SPEC
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Dire_Hit::
	giveitem ITEM_DIRE_HIT
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_X_Attack::
	giveitem ITEM_X_ATTACK
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_X_Defend::
	giveitem ITEM_X_DEFEND
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_X_Speed::
	giveitem ITEM_X_SPEED
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_X_Accuracy::
	giveitem ITEM_X_ACCURACY
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_X_Special::
	giveitem ITEM_X_SPECIAL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Poke_Doll::
	giveitem ITEM_POKE_DOLL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Fluffy_Tail::
	giveitem ITEM_FLUFFY_TAIL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Super_Repel::
	giveitem ITEM_SUPER_REPEL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Max_Repel::
	giveitem ITEM_MAX_REPEL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Escape_Rope::
	giveitem ITEM_ESCAPE_ROPE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Repel::
	giveitem ITEM_REPEL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Sun_Stone::
	giveitem ITEM_SUN_STONE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Moon_Stone::
	giveitem ITEM_MOON_STONE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Fire_Stone::
	giveitem ITEM_FIRE_STONE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Thunder_Stone::
	giveitem ITEM_THUNDER_STONE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Water_Stone::
	giveitem ITEM_WATER_STONE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Leaf_Stone::
	giveitem ITEM_LEAF_STONE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Tiny_Mushroom::
	giveitem ITEM_TINY_MUSHROOM
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Big_Mushroom::
	giveitem ITEM_BIG_MUSHROOM
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Pearl::
	giveitem ITEM_PEARL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Big_Pearl::
	giveitem ITEM_BIG_PEARL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Stardust::
	giveitem ITEM_STARDUST
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Star_Piece::
	giveitem ITEM_STAR_PIECE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Nugget::
	giveitem ITEM_NUGGET
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Heart_Scale::
	giveitem ITEM_HEART_SCALE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Orange_Mail::
	giveitem ITEM_ORANGE_MAIL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Harbor_Mail::
	giveitem ITEM_HARBOR_MAIL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Glitter_Mail::
	giveitem ITEM_GLITTER_MAIL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Mech_Mail::
	giveitem ITEM_MECH_MAIL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Wood_Mail::
	giveitem ITEM_WOOD_MAIL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Wave_Mail::
	giveitem ITEM_WAVE_MAIL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Bead_Mail::
	giveitem ITEM_BEAD_MAIL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Shadow_Mail::
	giveitem ITEM_SHADOW_MAIL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Tropic_Mail::
	giveitem ITEM_TROPIC_MAIL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Dream_Mail::
	giveitem ITEM_DREAM_MAIL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Fab_Mail::
	giveitem ITEM_FAB_MAIL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Retro_Mail::
	giveitem ITEM_RETRO_MAIL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Cheri_Berry::
	giveitem ITEM_CHERI_BERRY
	return

GetItem_Chesto_Berry::
	giveitem ITEM_CHESTO_BERRY
	return

GetItem_Pecha_Berry::
	giveitem ITEM_PECHA_BERRY
	return

GetItem_Rawst_Berry::
	giveitem ITEM_RAWST_BERRY
	return

GetItem_Aspear_Berry::
	giveitem ITEM_ASPEAR_BERRY
	return

GetItem_Leppa_Berry::
	giveitem ITEM_LEPPA_BERRY
	return

GetItem_Oran_Berry::
	giveitem ITEM_ORAN_BERRY
	return

GetItem_Persim_Berry::
	giveitem ITEM_PERSIM_BERRY
	return

GetItem_Lum_Berry::
	giveitem ITEM_LUM_BERRY
	return

GetItem_Sitrus_Berry::
	giveitem ITEM_SITRUS_BERRY
	return

GetItem_Figy_Berry::
	giveitem ITEM_FIGY_BERRY
	return

GetItem_Wiki_Berry::
	giveitem ITEM_WIKI_BERRY
	return

GetItem_Mago_Berry::
	giveitem ITEM_MAGO_BERRY
	return

GetItem_Aguav_Berry::
	giveitem ITEM_AGUAV_BERRY
	return

GetItem_Iapapa_Berry::
	giveitem ITEM_IAPAPA_BERRY
	return

GetItem_Razz_Berry::
	giveitem ITEM_RAZZ_BERRY
	return

GetItem_Bluk_Berry::
	giveitem ITEM_BLUK_BERRY
	return

GetItem_Nanab_Berry::
	giveitem ITEM_NANAB_BERRY
	return

GetItem_Wepear_Berry::
	giveitem ITEM_WEPEAR_BERRY
	return

GetItem_Pinap_Berry::
	giveitem ITEM_PINAP_BERRY
	return

GetItem_Pomeg_Berry::
	giveitem ITEM_POMEG_BERRY
	return

GetItem_Kelpsy_Berry::
	giveitem ITEM_KELPSY_BERRY
	return

GetItem_Qualot_Berry::
	giveitem ITEM_QUALOT_BERRY
	return

GetItem_Hondew_Berry::
	giveitem ITEM_HONDEW_BERRY
	return

GetItem_Grepa_Berry::
	giveitem ITEM_GREPA_BERRY
	return

GetItem_Tamato_Berry::
	giveitem ITEM_TAMATO_BERRY
	return

GetItem_Cornn_Berry::
	giveitem ITEM_CORNN_BERRY
	return

GetItem_Magost_Berry::
	giveitem ITEM_MAGOST_BERRY
	return

GetItem_Rabuta_Berry::
	giveitem ITEM_RABUTA_BERRY
	return

GetItem_Nomel_Berry::
	giveitem ITEM_NOMEL_BERRY
	return

GetItem_Spelon_Berry::
	giveitem ITEM_SPELON_BERRY
	return

GetItem_Pamtre_Berry::
	giveitem ITEM_PAMTRE_BERRY
	return

GetItem_Watmel_Berry::
	giveitem ITEM_WATMEL_BERRY
	return

GetItem_Durin_Berry::
	giveitem ITEM_DURIN_BERRY
	return

GetItem_Belue_Berry::
	giveitem ITEM_BELUE_BERRY
	return

GetItem_Liechi_Berry::
	giveitem ITEM_LIECHI_BERRY
	return

GetItem_Ganlon_Berry::
	giveitem ITEM_GANLON_BERRY
	return

GetItem_Salac_Berry::
	giveitem ITEM_SALAC_BERRY
	return

GetItem_Petaya_Berry::
	giveitem ITEM_PETAYA_BERRY
	return

GetItem_Apicot_Berry::
	giveitem ITEM_APICOT_BERRY
	return

GetItem_Lansat_Berry::
	giveitem ITEM_LANSAT_BERRY
	return

GetItem_Starf_Berry::
	giveitem ITEM_STARF_BERRY
	return

GetItem_Enigma_Berry::
	giveitem ITEM_ENIGMA_BERRY
	return

GetItem_Bright_Powder::
	giveitem ITEM_BRIGHT_POWDER
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_White_Herb::
	giveitem ITEM_WHITE_HERB
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Macho_Brace::
	giveitem ITEM_MACHO_BRACE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_EXP_SHARE::
	giveitem ITEM_EXP_SHARE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Quick_Claw::
	giveitem ITEM_QUICK_CLAW
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Soothe_Bell::
	giveitem ITEM_SOOTHE_BELL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Mental_Herb::
	giveitem ITEM_MENTAL_HERB
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Choice_Band::
	giveitem ITEM_CHOICE_BAND
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Kings_Rock::
	giveitem ITEM_KINGS_ROCK
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Silver_Powder::
	giveitem ITEM_SILVER_POWDER
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Amulet_Coin::
	giveitem ITEM_AMULET_COIN
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Cleanse_Tag::
	giveitem ITEM_CLEANSE_TAG
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Soul_Dew::
	giveitem ITEM_SOUL_DEW
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Deep_Sea_Scale::
	giveitem ITEM_DEEP_SEA_SCALE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Deep_Sea_Tooth::
	giveitem ITEM_DEEP_SEA_TOOTH
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Smoke_Ball::
	giveitem ITEM_SMOKE_BALL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Everstone::
	giveitem ITEM_EVERSTONE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Focus_Band::
	giveitem ITEM_FOCUS_BAND
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Lucky_Egg::
	giveitem ITEM_LUCKY_EGG
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Scope_Lens::
	giveitem ITEM_SCOPE_LENS
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Metal_Coat::
	giveitem ITEM_METAL_COAT
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Leftovers::
	giveitem ITEM_LEFTOVERS
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Dragon_Scale::
	giveitem ITEM_DRAGON_SCALE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Light_Ball::
	giveitem ITEM_LIGHT_BALL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Soft_Sand::
	giveitem ITEM_SOFT_SAND
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Hard_Stone::
	giveitem ITEM_HARD_STONE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Miracle_Seed::
	giveitem ITEM_MIRACLE_SEED
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Black_Glasses::
	giveitem ITEM_BLACK_GLASSES
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Black_Belt::
	giveitem ITEM_BLACK_BELT
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Magnet::
	giveitem ITEM_MAGNET
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Mystic_Water::
	giveitem ITEM_MYSTIC_WATER
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Sharp_Beak::
	giveitem ITEM_SHARP_BEAK
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Poison_Barb::
	giveitem ITEM_POISON_BARB
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Never_Melt_Ice::
	giveitem ITEM_NEVER_MELT_ICE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Spell_Tag::
	giveitem ITEM_SPELL_TAG
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Twisted_Spoon::
	giveitem ITEM_TWISTED_SPOON
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Charcoal::
	giveitem ITEM_CHARCOAL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Dragon_Fang::
	giveitem ITEM_DRAGON_FANG
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Silk_Scarf::
	giveitem ITEM_SILK_SCARF
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Up_Grade::
	giveitem ITEM_UP_GRADE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Shell_Bell::
	giveitem ITEM_SHELL_BELL
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Sea_Incense::
	giveitem ITEM_SEA_INCENSE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Lax_Incense::
	giveitem ITEM_LAX_INCENSE
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Lucky_Punch::
	giveitem ITEM_LUCKY_PUNCH
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Metal_Powder::
	giveitem ITEM_METAL_POWDER
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Thick_Club::
	giveitem ITEM_THICK_CLUB
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Stick::
	giveitem ITEM_STICK
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Red_Scarf::
	giveitem ITEM_RED_SCARF
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Blue_Scarf::
	giveitem ITEM_BLUE_SCARF
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Pink_Scarf::
	giveitem ITEM_PINK_SCARF
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Green_Scarf::
	giveitem ITEM_GREEN_SCARF
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return

GetItem_Yellow_Scarf::
	giveitem ITEM_YELLOW_SCARF
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_ShowBagIsFull
	return


@****KEY ITEMS******


GetItem_Mach_Bike::
	giveitem ITEM_MACH_BIKE
	return

GetItem_Coin_Case::
	giveitem ITEM_COIN_CASE
	return

GetItem_Itemfinder::
	giveitem ITEM_ITEMFINDER
	return

GetItem_Old_Rod::
	checkitem ITEM_OLD_ROD, 1
	compare VAR_RESULT, FALSE
	goto_if_eq giveitem_Old_Rod
	checkitem ITEM_GOOD_ROD, 1
	compare VAR_RESULT, FALSE
	goto_if_eq giveitem_Good_Rod
	giveitem ITEM_SUPER_ROD
	return

GetItem_Good_Rod::
	checkitem ITEM_OLD_ROD, 1
	compare VAR_RESULT, FALSE
	goto_if_eq giveitem_Old_Rod
	checkitem ITEM_GOOD_ROD, 1
	compare VAR_RESULT, FALSE
	goto_if_eq giveitem_Good_Rod
	giveitem ITEM_SUPER_ROD
	return

GetItem_Super_Rod::
	checkitem ITEM_OLD_ROD, 1
	compare VAR_RESULT, FALSE
	goto_if_eq giveitem_Old_Rod
	checkitem ITEM_GOOD_ROD, 1
	compare VAR_RESULT, FALSE
	goto_if_eq giveitem_Good_Rod
	giveitem ITEM_SUPER_ROD
	return

giveitem_Old_Rod::
	giveitem ITEM_OLD_ROD
	return

giveitem_Good_Rod::
	giveitem ITEM_GOOD_ROD
	return

GetItem_SS_Ticket::
	giveitem ITEM_SS_TICKET
	setflag FLAG_RECEIVED_SS_TICKET
	return

GetItem_Contest_Pass::
	giveitem ITEM_CONTEST_PASS
	return

GetItem_Wailmer_Pail::
	giveitem ITEM_WAILMER_PAIL
	return

GetItem_Devon_Goods::
	giveitem ITEM_DEVON_GOODS
	return

GetItem_Soot_Sack::
	giveitem ITEM_SOOT_SACK
	return

GetItem_Basement_Key::
	giveitem ITEM_BASEMENT_KEY
	return

GetItem_Acro_Bike::
	giveitem ITEM_ACRO_BIKE
	return

GetItem_Pokeblock_Case::
	giveitem ITEM_POKEBLOCK_CASE
	return

GetItem_Letter::
	giveitem ITEM_LETTER
	return

GetItem_Eon_Ticket::
	giveitem ITEM_EON_TICKET
	return

GetItem_Red_Orb::
	giveitem ITEM_RED_ORB
	return

GetItem_Blue_Orb::
	giveitem ITEM_BLUE_ORB
	return

GetItem_Scanner::
	giveitem ITEM_SCANNER
	return

GetItem_Go_Goggles::
	giveitem ITEM_GO_GOGGLES
	return

GetItem_Meteorite::
	giveitem ITEM_METEORITE
	return

GetItem_Room_1_Key::
	giveitem ITEM_ROOM_1_KEY
	return

GetItem_Room_2_Key::
	giveitem ITEM_ROOM_2_KEY
	return

GetItem_Room_4_Key::
	giveitem ITEM_ROOM_4_KEY
	return

GetItem_Room_6_Key::
	giveitem ITEM_ROOM_6_KEY
	return

GetItem_Storage_Key::
	giveitem ITEM_STORAGE_KEY
	return

GetItem_Root_Fossil::
	giveitem ITEM_ROOT_FOSSIL
	return

GetItem_Claw_Fossil::
	giveitem ITEM_CLAW_FOSSIL
	return

GetItem_Devon_Scope::
	giveitem ITEM_DEVON_SCOPE
	return

GetItem_Magma_Emblem::
	giveitem ITEM_MAGMA_EMBLEM
	return

GetItem_Powder_Jar::
	giveitem ITEM_POWDER_JAR
	return

GetItem_Old_Sea_Map::
	giveitem ITEM_OLD_SEA_MAP
	return

GetItem_Mystic_Ticket::
	giveitem ITEM_MYSTIC_TICKET
	return

GetItem_Aurora_Ticket::
	giveitem ITEM_AURORA_TICKET
	return

GetItem_TM01::
	giveitem ITEM_TM01
	return

GetItem_TM02::
	giveitem ITEM_TM02
	return

GetItem_TM03::
	giveitem ITEM_TM03
	return

GetItem_TM04::
	giveitem ITEM_TM04
	return

GetItem_TM05::
	giveitem ITEM_TM05
	return

GetItem_TM06::
	giveitem ITEM_TM06
	return

GetItem_TM07::
	giveitem ITEM_TM07
	return

GetItem_TM08::
	giveitem ITEM_TM08
	return

GetItem_TM09::
	giveitem ITEM_TM09
	return

GetItem_TM10::
	giveitem ITEM_TM10
	return

GetItem_TM11::
	giveitem ITEM_TM11
	return

GetItem_TM12::
	giveitem ITEM_TM12
	return

GetItem_TM13::
	giveitem ITEM_TM13
	return

GetItem_TM14::
	giveitem ITEM_TM14
	return

GetItem_TM15::
	giveitem ITEM_TM15
	return

GetItem_TM16::
	giveitem ITEM_TM16
	return

GetItem_TM17::
	giveitem ITEM_TM17
	return

GetItem_TM18::
	giveitem ITEM_TM18
	return

GetItem_TM19::
	giveitem ITEM_TM19
	return

GetItem_TM20::
	giveitem ITEM_TM20
	return

GetItem_TM21::
	giveitem ITEM_TM21
	return

GetItem_TM22::
	giveitem ITEM_TM22
	return

GetItem_TM23::
	giveitem ITEM_TM23
	return

GetItem_TM24::
	giveitem ITEM_TM24
	return

GetItem_TM25::
	giveitem ITEM_TM25
	return

GetItem_TM26::
	giveitem ITEM_TM26
	return

GetItem_TM27::
	giveitem ITEM_TM27
	return

GetItem_TM28::
	giveitem ITEM_TM28
	return

GetItem_TM29::
	giveitem ITEM_TM29
	return

GetItem_TM30::
	giveitem ITEM_TM30
	return

GetItem_TM31::
	giveitem ITEM_TM31
	return

GetItem_TM32::
	giveitem ITEM_TM32
	return

GetItem_TM33::
	giveitem ITEM_TM33
	return

GetItem_TM34::
	giveitem ITEM_TM34
	return

GetItem_TM35::
	giveitem ITEM_TM35
	return

GetItem_TM36::
	giveitem ITEM_TM36
	return

GetItem_TM37::
	giveitem ITEM_TM37
	return

GetItem_TM38::
	giveitem ITEM_TM38
	return

GetItem_TM39::
	giveitem ITEM_TM39
	return

GetItem_TM40::
	giveitem ITEM_TM40
	return

GetItem_TM41::
	giveitem ITEM_TM41
	return

GetItem_TM42::
	giveitem ITEM_TM42
	return

GetItem_TM43::
	giveitem ITEM_TM43
	return

GetItem_TM44::
	giveitem ITEM_TM44
	return

GetItem_TM45::
	giveitem ITEM_TM45
	return

GetItem_TM46::
	giveitem ITEM_TM46
	return

GetItem_TM47::
	giveitem ITEM_TM47
	return

GetItem_TM48::
	giveitem ITEM_TM48
	return

GetItem_TM49::
	giveitem ITEM_TM49
	return

GetItem_TM50::
	giveitem ITEM_TM50
	return

GetItem_HM01::
	giveitem ITEM_HM01
	return

GetItem_HM02::
	giveitem ITEM_HM02
	return

GetItem_HM03::
	giveitem ITEM_HM03
	return

GetItem_HM04::
	giveitem ITEM_HM04
	return

GetItem_HM05::
	giveitem ITEM_HM05
	return

GetItem_HM06::
	giveitem ITEM_HM06
	return

GetItem_HM07::
	giveitem ITEM_HM07
	return

GetItem_HM08::
	giveitem ITEM_HM08
	return

Add_Var_Petalburg_Gym::
	addvar VAR_PETALBURG_GYM_STATE, 1
	return

GetItem_Stone_Badge::
	message RustboroCity_Gym_Text_ReceivedStoneBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare	
	setflag FLAG_BADGE01_GET
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_lt Add_Var_Petalburg_Gym
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_eq Common_EventScript_ReadyPetalburgGymForBattle
	return

GetItem_Knuckle_Badge::
	message DewfordTown_Gym_Text_ReceivedKnuckleBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare	
	setflag FLAG_BADGE02_GET
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_lt Add_Var_Petalburg_Gym
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_eq Common_EventScript_ReadyPetalburgGymForBattle
	return

GetItem_Dynamo_Badge::
	message MauvilleCity_Gym_Text_ReceivedDynamoBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare	
	setflag FLAG_BADGE03_GET
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_lt Add_Var_Petalburg_Gym
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_eq Common_EventScript_ReadyPetalburgGymForBattle
	return

GetItem_Heat_Badge::
	message LavaridgeTown_Gym_1F_Text_ReceivedHeatBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare	
	setflag FLAG_BADGE04_GET
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_lt Add_Var_Petalburg_Gym
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_eq Common_EventScript_ReadyPetalburgGymForBattle
	return

GetItem_Balance_Badge::
	message PetalburgCity_Gym_Text_ReceivedBalanceBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare
	setflag FLAG_BADGE05_GET
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_lt Add_Var_Petalburg_Gym
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_eq Common_EventScript_ReadyPetalburgGymForBattle
	return

GetItem_Feather_Badge::	
	message FortreeCity_Gym_Text_ReceivedFeatherBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare
	setflag FLAG_BADGE06_GET
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_lt Add_Var_Petalburg_Gym
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_eq Common_EventScript_ReadyPetalburgGymForBattle
	return

GetItem_Mind_Badge::
	message MossdeepCity_Gym_Text_ReceivedMindBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare
	setflag FLAG_BADGE07_GET
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_lt Add_Var_Petalburg_Gym
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_eq Common_EventScript_ReadyPetalburgGymForBattle
	return

GetItem_Rain_Badge::
	message SootopolisCity_Gym_1F_Text_ReceivedRainBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare
	setflag FLAG_BADGE08_GET
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_lt Add_Var_Petalburg_Gym
	compare VAR_PETALBURG_GYM_STATE, 6
	call_if_eq Common_EventScript_ReadyPetalburgGymForBattle
	return

GetItem_Pokedex::
	goto_if_set FLAG_SYS_POKEDEX_GET, EventScript_Give_National_Dex
	playfanfare MUS_OBTAIN_ITEM
	message LittlerootTown_ProfessorBirchsLab_Text_ReceivedPokedex
	waitfanfare
	setflag FLAG_SYS_POKEDEX_GET
	special SetUnlockedPokedexFlags
	return

GetItem_National_Dex::
	goto_if_set FLAG_SYS_POKEDEX_GET, EventScript_Give_National_Dex
	playfanfare MUS_OBTAIN_ITEM
	message LittlerootTown_ProfessorBirchsLab_Text_ReceivedPokedex
	waitfanfare
	setflag FLAG_SYS_POKEDEX_GET
	special SetUnlockedPokedexFlags
	return

EventScript_Give_National_Dex::
	playfanfare MUS_OBTAIN_ITEM
	message LittlerootTown_ProfessorBirchsLab_Text_PokedexUpgradedToNational
	waitmessage
	waitfanfare
	setflag FLAG_SYS_NATIONAL_DEX
	special EnableNationalPokedex
	return

GetItem_Running_Shoes::
	playfanfare MUS_OBTAIN_ITEM
	message LittlerootTown_Text_SwitchShoesWithRunningShoes
	waitfanfare
	setflag FLAG_SYS_B_DASH
	return

GetItem_PokeNav::
	playfanfare MUS_OBTAIN_ITEM
	message RustboroCity_DevonCorp_3F_Text_ReceivedPokenav
	waitfanfare
	setflag FLAG_SYS_POKENAV_GET
	return

GetItem_Frontier_Pass::
	playfanfare MUS_OBTAIN_ITEM
	message BattleFrontier_ReceptionGate_Text_ObtainedFrontierPass
	waitfanfare
	waitmessage
	msgbox BattleFrontier_ReceptionGate_Text_PlacedTrainerCardInFrontierPass, MSGBOX_DEFAULT
	setflag FLAG_SYS_FRONTIER_PASS
	return

GetItem_Ability_Silver::
	setvar VAR_FRONTIER_FACILITY, 0
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattleTowerBattleRoom_Text_ReceivedAbilitySymbol	
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Ability_Gold::
	setvar VAR_FRONTIER_FACILITY, 0
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattleTowerBattleRoom_Text_AbilitySymbolTookGoldenShine
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Tactics_Silver::
	setvar VAR_FRONTIER_FACILITY, 1
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattleDomeBattleRoom_Text_ReceivedTacticsSymbol
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Tactics_Gold::
	setvar VAR_FRONTIER_FACILITY, 1
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattleDomeBattleRoom_Text_TacticsSymbolTookGoldenShine
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Spirit_Silver::
	setvar VAR_FRONTIER_FACILITY, 2
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattlePalaceBattleRoom_Text_ReceivedSpiritsSymbol
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Spirit_Gold::
	setvar VAR_FRONTIER_FACILITY, 2
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattlePalaceBattleRoom_Text_SpiritsSymbolTookGoldenShine
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Guts_Silver::
	setvar VAR_FRONTIER_FACILITY, 3
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattleArenaBattleRoom_Text_ReceivedGutsSymbol	
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Guts_Gold::
	setvar VAR_FRONTIER_FACILITY, 3
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattleArenaBattleRoom_Text_GutsSymbolTookGoldenShine
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Knowledge_Silver::
	setvar VAR_FRONTIER_FACILITY, 4
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattleFactoryBattleRoom_Text_ReceivedKnowledgeSymbol
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Knowledge_Gold::
	setvar VAR_FRONTIER_FACILITY, 4
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattleFactoryBattleRoom_Text_KnowledgeSymbolTookGoldenShine
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Luck_Silver::
	setvar VAR_FRONTIER_FACILITY, 5
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattlePikeRoomNormal_Text_ReceivedLuckSymbol	
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Luck_Gold::
	setvar VAR_FRONTIER_FACILITY, 5
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattlePikeRoomNormal_Text_LuckSymbolTookGoldenShine
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Brave_Silver::
	setvar VAR_FRONTIER_FACILITY, 6 
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattlePyramidTop_Text_ReceivedBraveSymbol
	waitmessage
	waitfanfare
	frontier_givesymbol
	return

GetItem_Brave_Gold::
	setvar VAR_FRONTIER_FACILITY, 6 
	playfanfare MUS_OBTAIN_SYMBOL
	message BattleFrontier_BattlePyramidTop_Text_BraveSymbolTookGoldenShine
	waitmessage
	waitfanfare
	frontier_givesymbol
	return


























